'use strict';
function assert(ok,message){if(!ok){const e=new Error(message);e.status=422;throw e;}}
function context(user,tenantId,roles){assert(user&&user.id,'authenticated actor required');assert(tenantId,'x-tenant-id is required');if(user.tenantId||user.tenant_id)assert((user.tenantId||user.tenant_id)===tenantId,'tenant mismatch');const role=user.role||'viewer';assert(roles.includes(role),'role not authorized');return{tenantId,actorId:String(user.id),role};}
function validateIncident(input){assert(/^[A-Za-z0-9._:-]{3,128}$/.test(input.idempotencyKey||''),'invalid idempotencyKey');assert(/^[A-Za-z0-9._:-]{3,128}$/.test(input.incidentKey||''),'invalid incidentKey');assert(['monitoring','minor','major','critical'].includes(input.severity),'invalid severity');assert(String(input.commanderId||'').trim(),'incident commander is required');return input;}
function validateMessage(input,sources){assert(['status_page','email','sms','social','press','internal'].includes(input.channel),'invalid channel');assert(String(input.body||'').trim().length>=20,'message body is too short');assert(Array.isArray(input.sourceCitations)&&input.sourceCitations.length>0,'authoritative source citations are required');const ids=new Set(sources.map(s=>String(s.id)));assert(input.sourceCitations.every(id=>ids.has(String(id))),'message cites an unverified source');assert(input.accessibilityEvaluation&&input.accessibilityEvaluation.passed===true,'accessibility evaluation must pass');assert(String(input.consistencyKey||'').trim().length>=3,'consistencyKey is required');return input;}
function canPublish({incident,message,approvals,sources,actor}){assert(incident&&incident.verification_state==='verified','incident must be verified');assert(message&&['review','approved','scheduled'].includes(message.state),'message is not reviewable for publication');assert(actor&&['publisher','incident_commander','admin'].includes(actor.role),'publishing authority is required');assert(sources.length>0&&sources.every(s=>!s.valid_until||new Date(s.valid_until)>new Date()),'current authoritative evidence is required');for(const gate of ['incident_command','communications'])assert(approvals.some(a=>a.gate===gate&&a.decision==='approved'),`${gate} approval is required`);return true;}
function validateDeliveryResult(input){assert(['delivered','partially_delivered','failed'].includes(input.status),'invalid delivery status');assert(Number.isInteger(input.acceptedCount)&&input.acceptedCount>=0,'acceptedCount is invalid');assert(Number.isInteger(input.failedCount)&&input.failedCount>=0,'failedCount is invalid');if(input.status==='failed')assert(String(input.errorCode||'').trim(),'failure requires an error code');return input;}
function correctionRequired(oldMessage,replacement,reason){assert(oldMessage&&oldMessage.state==='published','only published messages can be corrected');assert(replacement&&replacement.parent_version_id===oldMessage.id,'replacement must descend from published message');assert(String(reason||'').trim().length>=5,'correction reason is required');return true;}
module.exports={context,validateIncident,validateMessage,canPublish,validateDeliveryResult,correctionRequired};
