-- AI Crisis Communication Agent - Seed Data
-- Run after init.sql

-- Users (15 entries, first one is admin)
INSERT INTO users (email, password_hash, name, role) VALUES
('admin@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Admin User', 'admin'),
('sarah.chen@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Sarah Chen', 'manager'),
('james.wilson@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'James Wilson', 'analyst'),
('maria.garcia@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Maria Garcia', 'manager'),
('robert.johnson@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Robert Johnson', 'analyst'),
('lisa.wang@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Lisa Wang', 'user'),
('david.brown@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'David Brown', 'user'),
('emily.taylor@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Emily Taylor', 'analyst'),
('michael.lee@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Michael Lee', 'manager'),
('jennifer.martinez@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Jennifer Martinez', 'user'),
('daniel.kim@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Daniel Kim', 'analyst'),
('amanda.white@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Amanda White', 'user'),
('chris.anderson@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Chris Anderson', 'manager'),
('rachel.davis@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Rachel Davis', 'analyst'),
('kevin.thompson@crisiscomm.ai', '$2b$10$rQEY1f0IKAFU.YFuQxwBXONMkGTIOCNjGSMKfBzPBOm8sJ/KqZHCm', 'Kevin Thompson', 'user')
ON CONFLICT (email) DO NOTHING;

-- Crisis Incidents (15 entries)
INSERT INTO crisis_incidents (title, description, severity, status, category, location, affected_stakeholders, lead_responder) VALUES
('Chemical Spill at Plant B', 'A chemical storage tank ruptured releasing 500 gallons of industrial solvent into the surrounding area. Emergency containment measures have been activated.', 'critical', 'active', 'Environmental', 'Houston, TX - Plant B', 'Local residents, EPA, employees, media', 'Sarah Chen'),
('Data Breach - Customer Records', 'Unauthorized access detected to customer database containing approximately 50,000 records including names, emails, and encrypted payment info.', 'critical', 'active', 'Cybersecurity', 'Corporate HQ - Server Room 3', 'Customers, shareholders, regulators', 'James Wilson'),
('Product Recall - Model X500', 'Safety defect identified in Model X500 product line. Potential overheating issue in battery component affecting units manufactured between Jan-Mar 2026.', 'high', 'monitoring', 'Product Safety', 'National - All Distribution Centers', 'Consumers, retailers, supply chain partners', 'Maria Garcia'),
('Executive Misconduct Allegations', 'Media reports alleging financial misconduct by CFO. Board has initiated internal investigation. Stock price dropped 8% in pre-market trading.', 'high', 'active', 'Reputation', 'Corporate Headquarters', 'Shareholders, board members, employees, regulators', 'Robert Johnson'),
('Factory Fire - Warehouse District', 'Major fire broke out in warehouse facility destroying inventory worth $2M. No injuries reported. Fire department on scene.', 'high', 'monitoring', 'Operational', 'Newark, NJ - Warehouse 7', 'Employees, insurance, supply chain, customers', 'Sarah Chen'),
('Social Media Viral Complaint', 'Customer video showing product failure went viral with 2M+ views. Negative sentiment trending on Twitter and TikTok.', 'medium', 'active', 'Reputation', 'Online - Social Media Platforms', 'Customers, brand advocates, media', 'Emily Taylor'),
('Labor Strike Announcement', 'Union representing 3,000 workers announced plans for strike action starting next Monday over wage disputes.', 'high', 'active', 'Labor Relations', 'Detroit, MI - Manufacturing Plant', 'Employees, union, customers, suppliers', 'Michael Lee'),
('Supply Chain Disruption', 'Key supplier in Taiwan halted operations due to earthquake. Expected 6-8 week delay on critical components.', 'medium', 'monitoring', 'Supply Chain', 'Taiwan - Supplier Facilities', 'Production team, customers, investors', 'Lisa Wang'),
('Regulatory Investigation', 'FDA announced investigation into compliance practices at our pharmaceutical division. Preliminary inquiry stage.', 'high', 'active', 'Regulatory', 'Washington, DC - FDA Office', 'Regulators, patients, healthcare providers, investors', 'Daniel Kim'),
('Workplace Safety Incident', 'Employee injured in manufacturing line accident. OSHA notification required. Worker hospitalized with non-life-threatening injuries.', 'medium', 'resolved', 'Workplace Safety', 'Chicago, IL - Plant A', 'Employees, OSHA, union, families', 'Amanda White'),
('Misinformation Campaign', 'Coordinated disinformation campaign on social media spreading false claims about product ingredients. Bot activity detected.', 'medium', 'active', 'Reputation', 'Online - Multiple Platforms', 'Consumers, media, health organizations', 'Rachel Davis'),
('Natural Disaster Response', 'Hurricane approaching Gulf Coast facilities. Evacuation plans activated for 3 locations. Business continuity plans in effect.', 'critical', 'active', 'Natural Disaster', 'Gulf Coast - LA, MS, AL', 'Employees, communities, customers, government', 'Chris Anderson'),
('Merger Leak - Confidential', 'Details of pending acquisition leaked to financial press before official announcement. SEC implications being assessed.', 'high', 'monitoring', 'Financial', 'New York, NY', 'Shareholders, SEC, employees, target company', 'Kevin Thompson'),
('Customer Data Privacy Complaint', 'Class action lawsuit filed alleging improper data sharing practices with third-party advertisers.', 'medium', 'active', 'Legal', 'San Francisco, CA - Federal Court', 'Customers, legal team, regulators, advertisers', 'Jennifer Martinez'),
('Environmental Protest', 'Environmental activist group staging protests outside corporate headquarters. Media coverage increasing. 200+ protesters present.', 'low', 'monitoring', 'Reputation', 'Corporate Headquarters', 'Activists, media, employees, community', 'David Brown')
ON CONFLICT DO NOTHING;

-- Media Monitoring (15 entries)
INSERT INTO media_monitoring (source, title, url, sentiment, reach, platform, summary, published_at) VALUES
('CNN', 'Breaking: Major Chemical Spill Reported at Industrial Plant', 'https://cnn.com/2026/03/chemical-spill', 'negative', 5000000, 'TV/Online', 'CNN reporting on the chemical spill at Plant B with aerial footage showing containment efforts. Environmental impact assessment pending.', '2026-03-17 14:30:00'),
('Reuters', 'Company Faces Data Breach Affecting 50K Customers', 'https://reuters.com/2026/03/data-breach', 'negative', 3000000, 'Wire Service', 'Reuters wire story detailing the scope of the data breach. Cybersecurity experts comment on response timeline.', '2026-03-17 16:00:00'),
('Wall Street Journal', 'Stock Tumbles on CFO Misconduct Reports', 'https://wsj.com/2026/03/cfo-misconduct', 'negative', 2500000, 'Print/Online', 'WSJ deep dive into the financial misconduct allegations. Analyst downgrades expected.', '2026-03-16 08:00:00'),
('TikTok Viral', '@consumer_advocate Product Failure Video', 'https://tiktok.com/@consumer_advocate/viral', 'negative', 2100000, 'Social Media', 'Viral video showing product malfunction. Comments section flooded with similar complaints. 50K+ shares.', '2026-03-15 19:00:00'),
('Bloomberg', 'Company Initiates Product Recall for X500 Line', 'https://bloomberg.com/2026/03/recall-x500', 'neutral', 1800000, 'Financial News', 'Bloomberg coverage of the product recall. Estimated cost impact of $15-20M discussed.', '2026-03-16 10:30:00'),
('Local NBC Affiliate', 'Warehouse Fire Destroys Millions in Inventory', 'https://nbclocal.com/2026/03/warehouse-fire', 'negative', 500000, 'Local TV', 'Local news coverage of the warehouse fire with on-scene reporting. Community concerns about air quality.', '2026-03-17 22:00:00'),
('Twitter/X Trending', '#BoycottCompany Trending Nationally', 'https://twitter.com/trending/boycott', 'negative', 8000000, 'Social Media', 'Hashtag trending with 100K+ tweets. Mix of genuine concerns and coordinated amplification detected.', '2026-03-17 12:00:00'),
('Forbes', 'Crisis Management: How Companies Should Respond to Data Breaches', 'https://forbes.com/2026/03/crisis-management', 'neutral', 1200000, 'Online Magazine', 'Forbes article referencing the data breach as a case study. Expert opinions on best practices.', '2026-03-17 09:00:00'),
('Associated Press', 'Union Workers Prepare for Strike Action', 'https://ap.com/2026/03/union-strike', 'neutral', 4000000, 'Wire Service', 'AP coverage of the upcoming labor strike with union leadership quotes and company response statement.', '2026-03-16 15:00:00'),
('CNBC', 'Supply Chain Disruption Could Impact Q2 Earnings', 'https://cnbc.com/2026/03/supply-chain', 'negative', 2000000, 'Financial TV', 'CNBC segment analyzing potential financial impact of Taiwan supplier shutdown on quarterly results.', '2026-03-15 11:00:00'),
('New York Times', 'FDA Launches Investigation into Pharma Division', 'https://nytimes.com/2026/03/fda-investigation', 'negative', 3500000, 'Print/Online', 'NYT investigative report revealing details of FDA inquiry. Former employees quoted anonymously.', '2026-03-14 07:00:00'),
('Reddit r/technology', 'Data Breach Discussion Thread - 10K+ Upvotes', 'https://reddit.com/r/technology/data-breach', 'negative', 800000, 'Social Media', 'Reddit discussion thread with technical analysis of the breach. Security researchers weighing in.', '2026-03-17 20:00:00'),
('Guardian', 'Environmental Groups Demand Action After Chemical Spill', 'https://theguardian.com/2026/03/chemical-spill-response', 'negative', 2800000, 'Print/Online', 'Guardian article featuring environmental group statements and demands for stricter regulations.', '2026-03-18 06:00:00'),
('Industry Trade Journal', 'Product Safety Standards Under Review Following Recall', 'https://industrytrade.com/2026/03/safety-review', 'neutral', 200000, 'Trade Publication', 'Industry journal examining broader implications of the recall for manufacturing standards.', '2026-03-16 14:00:00'),
('Instagram', 'Employee Advocacy Posts Gaining Traction', 'https://instagram.com/company/employee-stories', 'positive', 350000, 'Social Media', 'Employee-generated content showing safety measures and community support efforts gaining positive engagement.', '2026-03-17 10:00:00')
ON CONFLICT DO NOTHING;

-- Stakeholders (15 entries)
INSERT INTO stakeholders (name, organization, role, email, phone, priority, relationship, notes) VALUES
('Dr. Patricia Hernandez', 'EPA Region 6', 'Regional Administrator', 'p.hernandez@epa.gov', '+1-214-555-0101', 'primary', 'Regulatory', 'Key contact for environmental incidents in TX region. Responsive to direct outreach.'),
('Mark Sullivan', 'Sullivan & Partners Law', 'Lead Counsel', 'm.sullivan@sullivanlaw.com', '+1-212-555-0202', 'primary', 'Legal Counsel', 'External crisis legal advisor. 20+ years experience in corporate crisis management.'),
('Angela Foster', 'National Consumer Safety Board', 'Commissioner', 'a.foster@ncsb.gov', '+1-202-555-0303', 'primary', 'Regulatory', 'Commissioner overseeing product safety. Met at industry conference last quarter.'),
('Tom Richards', 'ABC News Network', 'Senior Correspondent', 't.richards@abcnews.com', '+1-310-555-0404', 'primary', 'Media', 'Covers corporate stories nationally. Fair but persistent. Prefers exclusive interviews.'),
('Linda Chang', 'Investor Relations Group', 'Managing Director', 'l.chang@irgroup.com', '+1-415-555-0505', 'primary', 'Investor Relations', 'Manages communications with top 20 institutional investors. Critical during stock-moving events.'),
('Robert Okafor', 'City Council - Houston', 'Council Member District 5', 'r.okafor@houstontx.gov', '+1-713-555-0606', 'secondary', 'Government', 'Local government representative for Plant B district. Has been supportive but demands transparency.'),
('Dr. Susan Park', 'State Health Department', 'Chief Medical Officer', 's.park@statehealth.gov', '+1-512-555-0707', 'secondary', 'Regulatory', 'Relevant for health impact assessments. Quick response team available.'),
('Marcus Webb', 'United Workers Union', 'President', 'm.webb@uwunion.org', '+1-313-555-0808', 'primary', 'Labor', 'Union president leading strike negotiations. Open to dialogue but firm on demands.'),
('Cynthia Morales', 'Green Earth Alliance', 'Executive Director', 'c.morales@greenearth.org', '+1-503-555-0909', 'secondary', 'Activist/NGO', 'Leads environmental advocacy campaigns. Can amplify or de-escalate public pressure.'),
('Jason Park', 'TechSecure Consulting', 'CISO Consultant', 'j.park@techsecure.com', '+1-650-555-1010', 'primary', 'Consultant', 'Cybersecurity incident response lead. Available 24/7 for breach support.'),
('Diana Rodriguez', 'Major Retail Chain', 'VP of Procurement', 'd.rodriguez@retailchain.com', '+1-479-555-1111', 'secondary', 'Customer/Partner', 'Largest retail partner. Concerned about product recall impact on shelf space.'),
('William Chen', 'Taiwan Semiconductor Co.', 'VP Operations', 'w.chen@taiwansemi.com', '+886-2-555-1212', 'primary', 'Supplier', 'Key contact at disrupted supplier. Working on alternative supply arrangements.'),
('Nancy O''Brien', 'Insurance Corp of America', 'Claims Director', 'n.obrien@insurancecorp.com', '+1-860-555-1313', 'secondary', 'Insurance', 'Handling claims for warehouse fire and potential liability claims.'),
('Professor Alan Wright', 'MIT Crisis Communications Lab', 'Director', 'a.wright@mit.edu', '+1-617-555-1414', 'tertiary', 'Academic Advisor', 'Academic advisor on crisis communication strategy. Available for expert commentary.'),
('Karen Mitchell', 'Community Action Network', 'Community Organizer', 'k.mitchell@communityaction.org', '+1-713-555-1515', 'secondary', 'Community', 'Local community leader near Plant B. Can help facilitate town hall meetings.')
ON CONFLICT DO NOTHING;

-- Response Templates (15 entries)
INSERT INTO response_templates (name, category, template_text, variables, use_case, tone, last_used) VALUES
('Initial Crisis Acknowledgment', 'General', 'We are aware of {{incident_description}} and are taking immediate action. The safety and well-being of {{affected_parties}} is our top priority. We have activated our crisis response team and are working with {{authorities}} to address the situation. We will provide updates as more information becomes available.', 'incident_description, affected_parties, authorities', 'First public statement when crisis breaks', 'Empathetic, Authoritative', '2026-03-17 10:00:00'),
('Data Breach Notification', 'Cybersecurity', 'We are writing to inform you that on {{date}}, we discovered unauthorized access to {{system_affected}}. The potentially affected data includes {{data_types}}. We immediately {{actions_taken}} and have engaged {{security_firm}} to conduct a thorough investigation. We are offering {{remediation}} to all affected individuals.', 'date, system_affected, data_types, actions_taken, security_firm, remediation', 'Notifying affected individuals of data breach', 'Transparent, Reassuring', '2026-03-17 16:30:00'),
('Product Recall Statement', 'Product Safety', 'We are voluntarily recalling {{product_name}} due to {{issue_description}}. This affects {{units_affected}} units manufactured between {{date_range}}. Consumers should {{consumer_action}}. We sincerely apologize for any inconvenience and are committed to {{resolution}}.', 'product_name, issue_description, units_affected, date_range, consumer_action, resolution', 'Public announcement of product recall', 'Concerned, Action-oriented', '2026-03-16 11:00:00'),
('Environmental Incident Response', 'Environmental', 'We are responding to {{incident_type}} at our {{location}} facility. Our emergency response team has implemented {{containment_measures}}. We are working closely with {{regulatory_bodies}} and environmental experts to {{remediation_plan}}. The health and safety of our community is paramount.', 'incident_type, location, containment_measures, regulatory_bodies, remediation_plan', 'Environmental incident public statement', 'Responsible, Proactive', '2026-03-17 15:00:00'),
('Investor Communication', 'Financial', 'Dear Shareholders, We want to address {{issue}} directly. {{context}}. Our management team is {{actions}}. We remain committed to {{commitments}} and will provide a detailed update during {{next_communication}}. We appreciate your continued confidence.', 'issue, context, actions, commitments, next_communication', 'Communication to shareholders during crisis', 'Professional, Reassuring', '2026-03-16 09:00:00'),
('Employee Internal Memo', 'Internal', 'Team, As you may be aware, {{situation}}. I want to assure you that {{leadership_actions}}. Your role during this time is {{employee_guidance}}. Please direct all media inquiries to {{media_contact}}. We will hold a company-wide briefing on {{briefing_date}}.', 'situation, leadership_actions, employee_guidance, media_contact, briefing_date', 'Internal communication to employees', 'Supportive, Direct', '2026-03-17 08:00:00'),
('Social Media Quick Response', 'Social Media', 'We hear your concerns about {{issue}}. We take this seriously and are {{action}}. For the latest updates, visit {{link}}. If you need immediate assistance, please contact {{contact_info}}.', 'issue, action, link, contact_info', 'Quick social media response to public concerns', 'Empathetic, Concise', '2026-03-17 13:00:00'),
('Media Statement - No Comment', 'Media', 'Thank you for reaching out. We are aware of {{topic}} and are currently {{status}}. We are not in a position to comment further at this time but will issue a formal statement by {{timeline}}. All inquiries should be directed to {{spokesperson}}.', 'topic, status, timeline, spokesperson', 'Holding statement when full response not ready', 'Professional, Measured', '2026-03-16 12:00:00'),
('Community Outreach Letter', 'Community', 'Dear {{community_name}} Residents, We understand your concerns regarding {{issue}}. We want you to know that {{actions_taken}}. We are committed to {{commitments}}. We invite you to attend a community meeting on {{meeting_date}} at {{location}} to discuss this directly.', 'community_name, issue, actions_taken, commitments, meeting_date, location', 'Outreach to affected community members', 'Compassionate, Transparent', '2026-03-17 11:00:00'),
('Regulatory Response Letter', 'Regulatory', 'Dear {{regulator_name}}, In response to your inquiry dated {{date}} regarding {{subject}}, we provide the following information: {{response_details}}. We remain fully committed to compliance and have implemented {{corrective_actions}}. Please find enclosed {{attachments}}.', 'regulator_name, date, subject, response_details, corrective_actions, attachments', 'Formal response to regulatory inquiry', 'Formal, Cooperative', '2026-03-15 14:00:00'),
('Customer Apology', 'Customer Relations', 'Dear Valued Customer, We sincerely apologize for {{issue}}. We understand this has caused {{impact}} and we take full responsibility. To make this right, we are {{remedy}}. Your trust means everything to us and we are committed to {{improvement_plan}}.', 'issue, impact, remedy, improvement_plan', 'Apology to affected customers', 'Sincere, Accountable', '2026-03-16 16:00:00'),
('Labor Dispute Statement', 'Labor Relations', 'We value our {{workforce_description}} and respect their right to {{action}}. We remain committed to {{negotiation_stance}}. We have proposed {{proposal_summary}} and continue to engage in good-faith negotiations. Our goal is {{desired_outcome}}.', 'workforce_description, action, negotiation_stance, proposal_summary, desired_outcome', 'Public statement during labor disputes', 'Respectful, Firm', '2026-03-16 13:00:00'),
('Crisis Update Bulletin', 'General', 'UPDATE - {{timestamp}}: {{update_summary}}. Key developments: {{developments}}. Next steps: {{next_steps}}. For ongoing updates, monitor {{channels}}. Emergency contact: {{emergency_contact}}.', 'timestamp, update_summary, developments, next_steps, channels, emergency_contact', 'Ongoing crisis update bulletins', 'Factual, Clear', '2026-03-17 18:00:00'),
('Partnership/Supplier Notice', 'Supply Chain', 'Dear {{partner_name}}, We are writing to inform you of {{situation}} that may impact {{impact_area}}. We are taking the following steps: {{mitigation_steps}}. We anticipate {{timeline}} for resolution. Your dedicated contact for this matter is {{contact_person}}.', 'partner_name, situation, impact_area, mitigation_steps, timeline, contact_person', 'Notification to business partners/suppliers', 'Professional, Solution-oriented', '2026-03-15 10:00:00'),
('Post-Crisis Recovery Statement', 'General', 'Following {{crisis_description}}, we are pleased to share that {{resolution_summary}}. Key outcomes include: {{outcomes}}. We have implemented {{preventive_measures}} to prevent recurrence. We thank {{acknowledgments}} for their support throughout this period.', 'crisis_description, resolution_summary, outcomes, preventive_measures, acknowledgments', 'Statement after crisis has been resolved', 'Optimistic, Grateful', '2026-03-14 09:00:00')
ON CONFLICT DO NOTHING;

-- Press Releases (15 entries)
INSERT INTO press_releases (title, content, crisis_id, status, target_audience, ai_generated) VALUES
('Immediate Response to Chemical Spill at Plant B Facility', 'FOR IMMEDIATE RELEASE\n\nHouston, TX - March 17, 2026\n\nWe are responding to a chemical spill at our Plant B facility in Houston, Texas. At approximately 2:00 PM CST, a storage tank containing industrial solvent experienced a structural failure. Our emergency response team was activated within minutes and containment measures are in place.\n\nKey Facts:\n- No injuries have been reported\n- Containment barriers have been deployed\n- EPA has been notified and is on-site\n- Air quality monitoring stations have been activated\n\nWe are working closely with local authorities and environmental agencies to minimize impact and ensure public safety. Residents within a 1-mile radius are being advised to shelter in place as a precautionary measure.\n\nFor updates, visit our website or call our emergency hotline at 1-800-555-SAFE.', 1, 'published', 'General Public, Media, Regulators', false),
('Notice of Data Security Incident', 'FOR IMMEDIATE RELEASE\n\nMarch 17, 2026\n\nWe are writing to inform stakeholders of a data security incident discovered on March 17, 2026. Our cybersecurity team detected unauthorized access to a customer database.\n\nWhat Happened: Unauthorized access was gained to a database containing customer records.\nWhat Information Was Involved: Names, email addresses, and encrypted payment information.\nWhat We Are Doing: We have engaged leading cybersecurity firm TechSecure to investigate. All affected systems have been secured.\nWhat You Can Do: We recommend monitoring your financial accounts and enrolling in the complimentary credit monitoring service we are providing.\n\nWe take the protection of personal information extremely seriously and sincerely apologize for any concern this may cause.', 2, 'approved', 'Customers, Regulators, Media', false),
('Voluntary Product Recall: Model X500 Series', 'FOR IMMEDIATE RELEASE\n\nMarch 16, 2026\n\nWe are voluntarily recalling all Model X500 units manufactured between January and March 2026 due to a potential battery overheating issue identified during routine quality testing.\n\nApproximately 25,000 units are affected. No injuries have been reported to date. Customers should immediately stop using the product and contact us for a full refund or replacement.\n\nFree returns can be arranged by calling 1-800-555-RECALL or visiting our website. We apologize for the inconvenience and are committed to the highest safety standards.', 3, 'published', 'Consumers, Retailers, Media', false),
('Board of Directors Statement on Executive Investigation', 'FOR IMMEDIATE RELEASE\n\nMarch 16, 2026\n\nThe Board of Directors announces that it has initiated an independent investigation into allegations of financial misconduct involving a senior executive. The Board takes these allegations extremely seriously.\n\nThe executive in question has been placed on administrative leave pending the outcome of the investigation. An independent committee of the Board, supported by external counsel, will oversee the investigation.\n\nThe Company remains in full compliance with all regulatory requirements and continues to operate normally under the leadership of the existing management team.', 4, 'published', 'Investors, Regulators, Employees, Media', false),
('Update on Warehouse Fire Incident - Newark Facility', 'FOR IMMEDIATE RELEASE\n\nMarch 17, 2026\n\nWe can confirm that a fire occurred at our Newark, NJ warehouse facility earlier today. The fire has been contained and no injuries were reported. All employees were safely evacuated.\n\nThe cause of the fire is under investigation. We are working with our insurance providers and are implementing contingency plans to minimize supply chain disruption. Affected customer orders will be fulfilled from alternative locations.', 5, 'review', 'Customers, Partners, Media', false),
('Addressing Customer Concerns on Social Media', 'MEDIA STATEMENT\n\nMarch 17, 2026\n\nWe are aware of a video circulating on social media regarding one of our products. We take all customer feedback seriously and have reached out directly to the customer involved.\n\nOur quality assurance team is reviewing the specific incident. The safety and satisfaction of our customers is our top priority. We encourage any customers with concerns to contact our support team directly.', 6, 'draft', 'Social Media Users, Customers', true),
('Statement on Labor Negotiations', 'FOR IMMEDIATE RELEASE\n\nMarch 16, 2026\n\nWe remain committed to productive negotiations with the United Workers Union. We value our employees and recognize their important contributions.\n\nWe have presented a comprehensive proposal that includes wage increases, enhanced benefits, and improved working conditions. We urge both parties to continue negotiations in good faith to reach a resolution that benefits all stakeholders.', 7, 'approved', 'Employees, Union, Media, Community', false),
('Supply Chain Update for Partners and Customers', 'PARTNER COMMUNICATION\n\nMarch 16, 2026\n\nDue to recent natural disaster events affecting our supplier in Taiwan, we anticipate some delays in specific product lines. We are actively implementing our business continuity plans.\n\nAlternative suppliers have been identified and production ramp-up is expected within 3-4 weeks. We will work individually with affected partners to manage expectations and minimize impact.', 8, 'review', 'Partners, Customers', false),
('Response to FDA Inquiry', 'MEDIA STATEMENT\n\nMarch 15, 2026\n\nWe acknowledge the FDA preliminary inquiry into our pharmaceutical division operations. We are fully cooperating with the FDA and are committed to the highest standards of compliance.\n\nPatient safety is our paramount concern. Our products continue to meet all safety and efficacy standards. We are confident in our compliance programs and look forward to a constructive dialogue with the FDA.', 9, 'published', 'Healthcare Providers, Patients, Regulators, Media', false),
('Workplace Safety Commitment Following Incident', 'FOR IMMEDIATE RELEASE\n\nMarch 16, 2026\n\nFollowing a workplace incident at our Chicago facility, we want to reaffirm our unwavering commitment to employee safety. The affected employee is receiving full medical care and is expected to make a complete recovery.\n\nWe have conducted an immediate safety review and implemented additional protective measures. OSHA has been notified and we are fully cooperating with their review. All operations have been temporarily paused for a comprehensive safety audit.', 10, 'published', 'Employees, OSHA, Community', false),
('Combating Misinformation About Our Products', 'MEDIA STATEMENT\n\nMarch 17, 2026\n\nWe are aware of false claims circulating on social media regarding our product ingredients. These claims are categorically untrue. Our products meet all regulatory requirements and undergo rigorous quality testing.\n\nWe are working with social media platforms to address the spread of this misinformation and have engaged independent laboratories to provide verified testing results, which will be published on our website.', 11, 'draft', 'Consumers, Media, Health Organizations', true),
('Hurricane Preparedness and Business Continuity Update', 'FOR IMMEDIATE RELEASE\n\nMarch 17, 2026\n\nAs Hurricane approaching Gulf Coast, we have activated comprehensive emergency plans for our facilities in Louisiana, Mississippi, and Alabama. Employee safety is our first priority.\n\nAll non-essential operations have been suspended. Employees have been advised to follow local evacuation orders. Our business continuity team is ensuring minimal disruption to customers and partners.', 12, 'published', 'Employees, Customers, Community, Government', false),
('Statement on Confidential Business Discussions', 'MEDIA STATEMENT\n\nMarch 16, 2026\n\nWe do not comment on market speculation or rumors regarding potential business transactions. As a matter of policy, we will make appropriate disclosures in accordance with regulatory requirements at the appropriate time.\n\nWe remain focused on executing our strategic plan and delivering value to our shareholders.', 13, 'approved', 'Investors, Media, Regulators', false),
('Response to Data Privacy Litigation', 'LEGAL NOTICE\n\nMarch 17, 2026\n\nWe are aware of the class action lawsuit filed regarding our data practices. We believe the allegations are without merit and intend to vigorously defend our position.\n\nWe maintain robust data privacy practices and comply with all applicable data protection regulations. We are committed to transparency in how we handle customer data.', 14, 'review', 'Customers, Legal Community, Regulators', false),
('Engaging with Community Stakeholders on Environmental Concerns', 'COMMUNITY NOTICE\n\nMarch 17, 2026\n\nWe welcome the opportunity to engage with community members and environmental groups regarding their concerns. We have invited representatives to participate in an open dialogue at our upcoming community forum.\n\nDate: March 22, 2026\nTime: 6:00 PM\nLocation: Community Center, 500 Main Street\n\nWe are committed to being a responsible corporate neighbor and value the perspectives of all stakeholders.', 15, 'draft', 'Community, Activists, Media', false)
ON CONFLICT DO NOTHING;

-- Social Media Responses (15 entries)
INSERT INTO social_media_responses (platform, message, crisis_id, status, tone, character_count, ai_generated) VALUES
('Twitter/X', 'We are aware of the situation at our Plant B facility and are taking immediate action. Emergency response teams are on-site. No injuries reported. Updates: [link] #SafetyFirst', 1, 'posted', 'Urgent, Professional', 168, false),
('Twitter/X', 'We take data security seriously. We have detected and contained a security incident. If you are a customer, please check your email for important information. More details: [link]', 2, 'posted', 'Transparent, Reassuring', 179, false),
('Facebook', 'Important Safety Notice: We are voluntarily recalling Model X500 units manufactured Jan-Mar 2026. Your safety is our priority. For return information, visit [link] or call 1-800-555-RECALL. We sincerely apologize for any inconvenience.', 3, 'posted', 'Concerned, Helpful', 237, false),
('LinkedIn', 'Our Board of Directors has taken swift and decisive action regarding recent allegations. An independent investigation is underway. We remain committed to the highest standards of corporate governance and transparency. Full statement: [link]', 4, 'posted', 'Professional, Authoritative', 243, false),
('Instagram', 'We want to address the video that has been shared about our product. We have reached out to the customer directly and our quality team is investigating. Your satisfaction matters to us. DM us if you have any concerns. #CustomerFirst', 6, 'posted', 'Empathetic, Responsive', 236, true),
('Twitter/X', 'Update on the Newark warehouse fire: All employees safe, fire contained. We are working to minimize any impact on deliveries. Thank you for your patience and understanding.', 5, 'posted', 'Calm, Informative', 171, false),
('Twitter/X', 'We value our dedicated workforce and remain at the negotiating table. We are committed to reaching a fair agreement that recognizes our employees contributions. #FairNegotiations', 7, 'scheduled', 'Respectful, Constructive', 180, false),
('Facebook', 'Due to a natural disaster affecting one of our key suppliers, some products may experience temporary delays. We are working hard to minimize disruption and will keep you updated. Thank you for your understanding.', 8, 'posted', 'Honest, Appreciative', 213, false),
('Twitter/X', 'We are fully cooperating with the FDA inquiry and are confident in our compliance practices. Patient safety remains our top priority. Statement: [link]', 9, 'posted', 'Professional, Confident', 149, false),
('TikTok', 'Safety is not just a policy - it is our culture. Following a recent incident, we have doubled down on safety training and protocols. Heres what we are doing to keep our team safe. [video link]', 10, 'draft', 'Authentic, Committed', 192, true),
('Twitter/X', 'False claims about our products are circulating online. Let us be clear: our products meet ALL regulatory standards. We are publishing independent lab results at [link]. Do not spread misinformation. #FactsFirst', 11, 'posted', 'Firm, Factual', 196, false),
('Facebook', 'Hurricane Update: The safety of our employees and communities comes first. We have activated emergency plans and are supporting local relief efforts. Stay safe. For employee resources: [link]', 12, 'posted', 'Caring, Urgent', 192, false),
('LinkedIn', 'We do not comment on market speculation. Our focus remains on delivering value through innovation and operational excellence. Stay tuned for our upcoming quarterly update.', 13, 'scheduled', 'Professional, Measured', 169, false),
('Twitter/X', 'We are committed to protecting your data privacy. We stand behind our data practices and will address the recent filing through proper legal channels. Your trust is paramount. [link]', 14, 'draft', 'Reassuring, Confident', 181, true),
('Instagram', 'We hear you, and we want to talk. Join us at our community forum on March 22 to discuss your environmental concerns face-to-face. Details in bio. Everyone is welcome. #CommunityFirst #OpenDialogue', 15, 'scheduled', 'Welcoming, Open', 199, false)
ON CONFLICT DO NOTHING;

-- Sentiment Analyses (15 entries)
INSERT INTO sentiment_analyses (text_input, sentiment_score, sentiment_label, key_phrases, emotions, source, ai_analysis) VALUES
('The chemical spill is an absolute disaster. How could they let this happen? The whole neighborhood could be affected!', -0.850, 'Very Negative', 'chemical spill, disaster, neighborhood affected', 'anger, fear, frustration', 'Twitter/X', 'Strong negative sentiment driven by fear of environmental and health impacts. High emotional intensity suggests potential for viral spread. Recommended response: immediate transparent communication with specific safety measures.'),
('Just got the data breach notification email. At least they are offering credit monitoring. Could be worse I guess.', -0.300, 'Slightly Negative', 'data breach, notification, credit monitoring', 'concern, resignation, mild approval', 'Reddit', 'Mixed sentiment with slight negative lean. Customer acknowledges company response efforts. The resigned tone suggests this could be converted to neutral with strong follow-up communication.'),
('Really impressed with how quickly they initiated the product recall. Shows they care about safety over profits.', 0.750, 'Positive', 'impressed, quick recall, safety over profits', 'approval, trust, respect', 'Facebook', 'Positive sentiment recognizing swift corporate action. This type of response can be amplified as a case study in effective crisis response. Customer trust is being maintained.'),
('Another day another corporate scandal. These executives think they can get away with anything.', -0.700, 'Negative', 'corporate scandal, executives, get away', 'cynicism, anger, distrust', 'Twitter/X', 'Negative sentiment reflecting broader anti-corporate sentiment rather than specific incident knowledge. Generic distrust pattern. Difficult to address individually but demonstrates need for strong governance messaging.'),
('The warehouse fire is concerning but glad no one was hurt. Hope they have good insurance.', -0.150, 'Neutral', 'warehouse fire, no one hurt, insurance', 'concern, relief', 'Local News Comments', 'Near-neutral sentiment with slight concern. Relief about safety outcomes is a positive signal. The insurance comment suggests pragmatic assessment rather than emotional response.'),
('This viral video is crazy! Their product literally exploded. Never buying from them again.', -0.900, 'Very Negative', 'viral video, exploded, never buying again', 'shock, anger, distrust', 'TikTok Comments', 'Extremely negative sentiment with strong purchase intent impact. The word literally suggests exaggeration. Need fact-based response showing actual product performance and safety testing results.'),
('As a union member I support the strike. We deserve better wages and conditions.', -0.400, 'Negative', 'union, strike, better wages, conditions', 'solidarity, determination, frustration', 'Twitter/X', 'Moderately negative toward company from labor perspective. Organized sentiment likely to be amplified by union communications. Negotiation-focused messaging recommended.'),
('Supply chain issues are going to hurt this stock. Selling my position.', -0.600, 'Negative', 'supply chain, hurt stock, selling', 'worry, urgency, loss aversion', 'StockTwits', 'Financial-focused negative sentiment with actionable intent (selling stock). Indicates investor confidence erosion. Need clear timeline and alternative supply communication for investor audience.'),
('The FDA investigation is routine. People are overreacting. The company has always been compliant.', 0.300, 'Slightly Positive', 'FDA, routine, overreacting, compliant', 'confidence, dismissiveness', 'LinkedIn', 'Positive sentiment from likely insider or informed stakeholder. Useful perspective to amplify in communications. Shows that balanced voices exist in the conversation.'),
('Shout out to the safety team for evacuating everyone during the factory incident. Real heroes.', 0.850, 'Very Positive', 'safety team, evacuating, heroes', 'gratitude, admiration, pride', 'Facebook', 'Highly positive sentiment focused on employee safety response. Excellent candidate for amplification. Humanizes the company response and highlights preparedness.'),
('The misinformation about their products is clearly a coordinated attack. I have used their products for years with no issues.', 0.500, 'Positive', 'misinformation, coordinated attack, no issues, years', 'loyalty, skepticism toward claims', 'Twitter/X', 'Positive brand advocacy sentiment. Customer identifying misinformation pattern aligns with company messaging. Consider engaging this user as a brand advocate.'),
('Praying for everyone in the path of the hurricane. Hope the company takes care of their workers.', 0.200, 'Slightly Positive', 'praying, hurricane, take care, workers', 'empathy, hope, concern', 'Facebook', 'Empathetic sentiment with positive expectations of company behavior. Community-oriented. Company response should match these caring expectations with concrete employee support actions.'),
('If the merger rumors are true this stock is going to moon. Loading up shares now.', 0.700, 'Positive', 'merger, stock, loading up shares', 'excitement, greed, optimism', 'Reddit/WallStreetBets', 'Speculative positive sentiment driven by merger rumors. Not based on fundamentals. Company should not engage with speculation but ensure regulatory compliance in communications.'),
('Just joined the class action lawsuit. Its time these companies respect our privacy.', -0.750, 'Negative', 'class action, privacy, respect', 'anger, determination, righteous indignation', 'Twitter/X', 'Strong negative sentiment with legal action intent. Represents organized opposition. Legal team should monitor this conversation thread. Do not engage directly due to litigation.'),
('Went to the community meeting. The company reps were actually very open and answered tough questions. Cautiously optimistic.', 0.600, 'Positive', 'community meeting, open, tough questions, cautiously optimistic', 'cautious approval, hope, engagement', 'Neighborhood Forum', 'Positive outcome from community engagement effort. Face-to-face communication proving effective. Validates community outreach strategy. Continue building on this momentum.')
ON CONFLICT DO NOTHING;

-- Crisis Simulations (15 entries)
INSERT INTO crisis_simulations (scenario_name, description, severity, objectives, participants, status, results, lessons_learned, scheduled_date) VALUES
('Cyber Attack Tabletop Exercise', 'Simulated ransomware attack on critical infrastructure systems including customer databases and operational technology.', 'critical', 'Test incident response plan, validate communication chains, assess recovery time objectives', 'IT Security Team, Executive Leadership, Legal, PR, Operations', 'completed', 'Response time: 45 min to detection, 2 hours to containment. Communication chain had 15-min gap between IT and Executive notification.', 'Need dedicated crisis communication channel. IT-to-leadership notification must be automated. Backup communication plan needed for system outages.', '2026-02-15 09:00:00'),
('Product Contamination Scenario', 'Simulated discovery of contaminated product on store shelves with potential health risks to consumers.', 'critical', 'Test recall procedures, validate stakeholder notification process, assess media response readiness', 'Quality Assurance, Supply Chain, Legal, PR, Customer Service', 'completed', 'Recall notification sent within 4 hours. Media statement ready within 2 hours. Retailer notification process identified as bottleneck.', 'Retailer contact database needs updating. Pre-drafted recall templates saved significant time. Customer service team needs additional training on recall scripts.', '2026-02-20 10:00:00'),
('Executive Crisis Drill', 'Scenario involving sudden CEO health emergency during major product launch event with live media coverage.', 'high', 'Test succession communication plan, validate spokesperson readiness, assess market impact response', 'Board Members, C-Suite, Investor Relations, PR, Legal', 'completed', 'Backup spokesperson identified and briefed within 30 minutes. Market communication drafted in 45 minutes. Board notification completed in 20 minutes.', 'Need more trained spokespersons. Pre-prepared holding statements essential. Investor relations team performed exceptionally well.', '2026-01-25 14:00:00'),
('Natural Disaster Response Drill', 'Simulated Category 4 hurricane impacting multiple operational facilities simultaneously with employee safety concerns.', 'critical', 'Test evacuation procedures, validate business continuity plan, assess employee communication effectiveness', 'Facilities Management, HR, Operations, Safety, IT', 'completed', 'Employee accounting completed in 3 hours for 5,000+ staff. Three facilities successfully transitioned to backup operations. Two communication gaps identified in remote locations.', 'Satellite communication backup critical for disaster scenarios. Employee emergency contact database 85% current - needs improvement. Remote work capabilities tested successfully.', '2026-03-01 08:00:00'),
('Social Media Crisis Simulation', 'Viral negative content scenario with coordinated bot amplification and mainstream media pickup.', 'medium', 'Test social media monitoring response time, validate escalation procedures, assess content approval workflow', 'Social Media Team, PR, Legal, Marketing, Customer Service', 'completed', 'First response within 15 minutes of detection. Escalation to management in 25 minutes. Legal review created 1-hour bottleneck for official response.', 'Need pre-approved response templates for common scenarios. Legal team should have dedicated crisis reviewer available. Social media team performed well under pressure.', '2026-02-10 13:00:00'),
('Supply Chain Disruption Exercise', 'Simulated simultaneous failure of two major suppliers with 60-day recovery timeline.', 'high', 'Test alternative supplier activation, validate inventory buffer adequacy, assess customer communication plan', 'Procurement, Operations, Sales, Customer Service, Finance', 'completed', 'Alternative suppliers identified within 24 hours (simulated). Inventory buffer sufficient for 3 weeks. Customer communication template effective but lacked personalization.', 'Maintain relationships with 3+ alternative suppliers per critical component. Inventory buffer should cover 6 weeks minimum. Customer communication should segment by impact level.', '2026-02-05 10:00:00'),
('Regulatory Raid Scenario', 'Simulated unannounced regulatory inspection with document requests and employee interviews.', 'high', 'Test document preservation procedures, validate employee guidance protocols, assess legal response readiness', 'Legal, Compliance, HR, Operations, Executive Leadership', 'completed', 'Legal team on-site within 45 minutes. Document hold implemented in 1 hour. Employee guidance distributed in 2 hours. Two compliance gaps identified.', 'All employees need annual training on regulatory interaction protocols. Document retention policies need quarterly review. Legal should have ready-bag with key documents.', '2026-01-15 11:00:00'),
('Workplace Violence Response', 'Simulated active threat scenario at corporate headquarters during business hours.', 'critical', 'Test lockdown procedures, validate law enforcement coordination, assess employee safety communication', 'Security, HR, Facilities, Executive Leadership, External Law Enforcement', 'completed', 'Lockdown initiated in 3 minutes. Law enforcement notified in 2 minutes. All-clear communication took 45 minutes - too slow. Employee accountability achieved in 2 hours.', 'Panic button system needs upgrade. Communication during lockdown relies too heavily on email - need SMS/app alerts. Regular lockdown drills critical. Counseling resources should be pre-arranged.', '2026-01-20 15:00:00'),
('Multi-site Environmental Incident', 'Simulated simultaneous environmental incidents at three different facilities requiring coordinated response.', 'critical', 'Test multi-site coordination, validate environmental response capacity, assess regulatory notification compliance', 'Environmental Health & Safety, Operations, Legal, PR, Government Affairs', 'planned', NULL, NULL, '2026-04-01 09:00:00'),
('Hostile Takeover Communication Drill', 'Simulated hostile acquisition attempt requiring rapid stakeholder communication and defense strategy.', 'high', 'Test poison pill communication, validate board notification speed, assess shareholder communication readiness', 'Board, Legal, Investor Relations, PR, Executive Leadership', 'planned', NULL, NULL, '2026-04-15 10:00:00'),
('Pandemic Resurgence Plan Test', 'Testing business continuity plans for a new pandemic wave affecting 40% of workforce simultaneously.', 'high', 'Test remote work scalability, validate essential worker policies, assess communication effectiveness', 'HR, IT, Operations, Executive Leadership, Facilities', 'planned', NULL, NULL, '2026-05-01 09:00:00'),
('Data Center Failure Scenario', 'Simulated catastrophic failure of primary data center with cascading service outages.', 'critical', 'Test disaster recovery procedures, validate failover systems, assess customer communication during outage', 'IT, Operations, Customer Service, PR, Executive Leadership', 'in_progress', NULL, NULL, '2026-03-18 10:00:00'),
('Brand Ambassador Controversy', 'Scenario where a major brand ambassador makes controversial public statements requiring brand distancing.', 'medium', 'Test partnership termination procedures, validate social media response strategy, assess brand impact mitigation', 'Marketing, PR, Legal, Social Media, Executive Leadership', 'planned', NULL, NULL, '2026-04-20 14:00:00'),
('International Sanctions Compliance', 'Simulated discovery of inadvertent sanctions violation through third-party supplier network.', 'high', 'Test compliance notification procedures, validate supply chain audit capabilities, assess regulatory response', 'Legal, Compliance, Procurement, Government Affairs, Finance', 'planned', NULL, NULL, '2026-05-10 11:00:00'),
('Mass Layoff Communication Exercise', 'Testing communication strategy and execution for a significant workforce reduction affecting 500+ employees.', 'high', 'Test HR communication cascade, validate media strategy, assess employee support program readiness', 'HR, Legal, PR, Executive Leadership, IT, Facilities', 'planned', NULL, NULL, '2026-05-15 09:00:00')
ON CONFLICT DO NOTHING;

-- Communication Logs (15 entries)
INSERT INTO communication_logs (crisis_id, channel, sender, recipient, message, direction, status) VALUES
(1, 'Phone', 'Sarah Chen', 'EPA Region 6 - Dr. Hernandez', 'Initial notification of chemical spill. Provided incident details, containment status, and requested EPA on-site inspection.', 'outbound', 'completed'),
(1, 'Email', 'EPA Region 6', 'Sarah Chen', 'Acknowledged notification. Inspection team dispatched. Requesting environmental impact assessment within 48 hours.', 'inbound', 'received'),
(2, 'Email', 'James Wilson', 'All Affected Customers', 'Data breach notification email sent to 50,000 affected customers with credit monitoring enrollment instructions.', 'outbound', 'sent'),
(2, 'Phone', 'TechSecure - Jason Park', 'James Wilson', 'Preliminary forensic analysis complete. Attack vector identified as compromised vendor credentials. Full report in 24 hours.', 'inbound', 'received'),
(3, 'Press Release', 'Maria Garcia', 'National Media', 'Product recall press release distributed via PR Newswire to all major media outlets and trade publications.', 'outbound', 'distributed'),
(4, 'Email', 'Board Secretary', 'All Board Members', 'Emergency board meeting scheduled for March 17 at 4:00 PM to discuss CFO investigation findings.', 'outbound', 'sent'),
(5, 'Phone', 'Sarah Chen', 'Insurance Corp - Nancy O''Brien', 'Filed initial claim for warehouse fire damage. Estimated loss $2M in inventory. Adjuster visit scheduled for March 19.', 'outbound', 'completed'),
(6, 'Social Media', 'Emily Taylor', 'Viral Video Customer', 'Direct message sent to customer offering replacement product and requesting phone call to discuss experience.', 'outbound', 'sent'),
(7, 'Meeting', 'Michael Lee', 'Union President - Marcus Webb', 'Face-to-face negotiation session. Presented revised wage proposal with 3.5% increase and enhanced benefits package.', 'outbound', 'completed'),
(9, 'Email', 'Daniel Kim', 'FDA Office of Compliance', 'Submitted preliminary compliance documentation package as requested. Offered facility tour and open-book inspection.', 'outbound', 'sent'),
(10, 'Phone', 'Amanda White', 'OSHA Regional Office', 'Mandatory incident report filed. Provided details of workplace injury, root cause analysis, and corrective actions taken.', 'outbound', 'completed'),
(12, 'SMS Broadcast', 'Chris Anderson', 'All Gulf Coast Employees', 'URGENT: Hurricane evacuation order in effect. Report to designated assembly points. Check email for detailed instructions.', 'outbound', 'delivered'),
(1, 'Press Conference', 'Sarah Chen', 'Media Pool', 'Held press conference at Plant B providing update on containment progress, environmental monitoring results, and community support measures.', 'outbound', 'completed'),
(2, 'Hotline', 'Customer Service', 'Multiple Callers', 'Received 847 calls to data breach hotline in first 6 hours. Average wait time: 4 minutes. 92% resolution rate.', 'inbound', 'ongoing'),
(14, 'Legal Filing', 'Legal Department', 'Federal Court', 'Filed motion to dismiss class action complaint. Submitted evidence of compliance with data privacy regulations.', 'outbound', 'filed')
ON CONFLICT DO NOTHING;

-- Team Members (15 entries)
INSERT INTO team_members (name, email, role, department, phone, availability, skills, assigned_crisis_id) VALUES
('Sarah Chen', 'sarah.chen@crisiscomm.ai', 'Crisis Communications Director', 'Communications', '+1-713-555-2001', 'busy', 'Crisis management, media relations, public speaking, strategic communications, stakeholder engagement', 1),
('James Wilson', 'james.wilson@crisiscomm.ai', 'Cybersecurity Communications Lead', 'IT Security', '+1-415-555-2002', 'busy', 'Cybersecurity, incident response, technical writing, data privacy, regulatory compliance', 2),
('Maria Garcia', 'maria.garcia@crisiscomm.ai', 'Product Safety Communications Manager', 'Quality & Safety', '+1-312-555-2003', 'busy', 'Product recalls, consumer safety, regulatory affairs, media relations, risk assessment', 3),
('Robert Johnson', 'robert.johnson@crisiscomm.ai', 'Corporate Affairs Manager', 'Legal & Compliance', '+1-212-555-2004', 'busy', 'Corporate governance, legal communications, investor relations, regulatory compliance', 4),
('Emily Taylor', 'emily.taylor@crisiscomm.ai', 'Social Media Crisis Manager', 'Digital Marketing', '+1-310-555-2005', 'available', 'Social media management, content strategy, community management, sentiment analysis, digital PR', 6),
('Michael Lee', 'michael.lee@crisiscomm.ai', 'Labor Relations Specialist', 'Human Resources', '+1-313-555-2006', 'busy', 'Labor law, union negotiations, employee communications, conflict resolution, mediation', 7),
('Lisa Wang', 'lisa.wang@crisiscomm.ai', 'Supply Chain Communications Analyst', 'Operations', '+1-408-555-2007', 'available', 'Supply chain management, vendor relations, business continuity, data analysis', 8),
('Daniel Kim', 'daniel.kim@crisiscomm.ai', 'Regulatory Affairs Specialist', 'Legal & Compliance', '+1-202-555-2008', 'busy', 'FDA regulations, pharmaceutical compliance, government affairs, policy analysis', 9),
('Amanda White', 'amanda.white@crisiscomm.ai', 'Workplace Safety Coordinator', 'Health & Safety', '+1-312-555-2009', 'available', 'OSHA compliance, safety training, incident investigation, emergency response, risk management', NULL),
('Chris Anderson', 'chris.anderson@crisiscomm.ai', 'Emergency Response Manager', 'Operations', '+1-504-555-2010', 'busy', 'Emergency management, disaster recovery, business continuity, logistics, employee safety', 12),
('Rachel Davis', 'rachel.davis@crisiscomm.ai', 'Media Monitoring Analyst', 'Communications', '+1-646-555-2011', 'available', 'Media monitoring, sentiment analysis, trend analysis, reporting, social listening', NULL),
('Kevin Thompson', 'kevin.thompson@crisiscomm.ai', 'Financial Communications Specialist', 'Investor Relations', '+1-212-555-2012', 'available', 'Financial reporting, investor communications, SEC compliance, market analysis', 13),
('Patricia Nguyen', 'patricia.nguyen@crisiscomm.ai', 'Community Relations Manager', 'Public Affairs', '+1-713-555-2013', 'available', 'Community engagement, public affairs, event planning, grassroots communications, stakeholder mapping', NULL),
('Thomas Martinez', 'thomas.martinez@crisiscomm.ai', 'Legal Communications Counsel', 'Legal', '+1-415-555-2014', 'busy', 'Legal writing, litigation support, media law, corporate law, crisis legal strategy', 14),
('Sophia Brooks', 'sophia.brooks@crisiscomm.ai', 'Training & Simulation Coordinator', 'Learning & Development', '+1-617-555-2015', 'available', 'Training design, crisis simulation, tabletop exercises, scenario planning, after-action reviews', NULL)
ON CONFLICT DO NOTHING;

-- Incident Timelines (15 entries)
INSERT INTO incident_timelines (crisis_id, event_title, event_description, event_type, timestamp, reported_by, impact_level) VALUES
(1, 'Tank Rupture Detected', 'Sensors detected pressure drop in Chemical Storage Tank 7. Automated alarm triggered.', 'detection', '2026-03-17 14:02:00', 'Automated Monitoring System', 'critical'),
(1, 'Emergency Response Activated', 'Plant B emergency response team deployed to containment area. Area evacuated within 8 minutes.', 'response', '2026-03-17 14:10:00', 'Plant Safety Manager', 'high'),
(1, 'EPA Notified', 'Formal notification sent to EPA Region 6 per regulatory requirements.', 'notification', '2026-03-17 14:25:00', 'Sarah Chen', 'medium'),
(1, 'Containment Barriers Deployed', 'Physical containment barriers fully deployed around spill perimeter. Estimated 500 gallons released.', 'response', '2026-03-17 14:45:00', 'Emergency Response Team', 'high'),
(1, 'Media Inquiries Begin', 'First media inquiries received from local Houston news stations.', 'media', '2026-03-17 15:00:00', 'PR Department', 'medium'),
(2, 'Anomalous Access Detected', 'Security monitoring tools flagged unusual database query patterns from an internal service account.', 'detection', '2026-03-17 09:30:00', 'Security Operations Center', 'critical'),
(2, 'Access Terminated', 'Compromised credentials revoked. Affected systems isolated from network.', 'response', '2026-03-17 10:15:00', 'IT Security Team', 'high'),
(2, 'Forensic Investigation Initiated', 'TechSecure engaged for forensic analysis. Evidence preservation procedures activated.', 'investigation', '2026-03-17 11:00:00', 'James Wilson', 'high'),
(2, 'Customer Notification Approved', 'Legal reviewed and approved customer breach notification template.', 'decision', '2026-03-17 15:00:00', 'Legal Department', 'medium'),
(3, 'Defect Identified in Testing', 'Routine quality testing revealed battery overheating in X500 units under specific conditions.', 'detection', '2026-03-14 11:00:00', 'Quality Assurance Lab', 'high'),
(3, 'Voluntary Recall Decision', 'Executive committee approved voluntary recall of all affected X500 units.', 'decision', '2026-03-15 16:00:00', 'CEO', 'critical'),
(3, 'CPSC Notification Filed', 'Consumer Product Safety Commission formally notified of voluntary recall.', 'notification', '2026-03-16 09:00:00', 'Maria Garcia', 'high'),
(7, 'Strike Notice Received', 'Formal 7-day strike notice received from United Workers Union leadership.', 'detection', '2026-03-10 08:00:00', 'HR Department', 'high'),
(12, 'Hurricane Watch Issued', 'National Weather Service issued hurricane watch for Gulf Coast including our facility locations.', 'detection', '2026-03-16 06:00:00', 'Chris Anderson', 'high'),
(12, 'Evacuation Order Activated', 'Company-wide evacuation order issued for all three Gulf Coast facilities.', 'response', '2026-03-17 08:00:00', 'Chris Anderson', 'critical')
ON CONFLICT DO NOTHING;

-- Risk Assessments (15 entries)
INSERT INTO risk_assessments (title, description, category, likelihood, impact, risk_score, mitigation_strategy, status, ai_analysis) VALUES
('Repeat Chemical Spill Risk', 'Risk of additional chemical storage tank failures at aging Plant B facility. Infrastructure is 25+ years old.', 'Environmental', 4, 5, 20, 'Immediate: Install additional sensors and automated shutoff valves. Short-term: Conduct full structural assessment of all tanks. Long-term: Plan phased replacement of aging infrastructure.', 'analyzing', 'AI analysis indicates that facilities of similar age have a 3x higher incident rate. Predictive maintenance data suggests Tank 3 and Tank 12 are next highest risk. ROI on preventive replacement is positive within 2 years when factoring potential spill costs.'),
('Secondary Data Breach Attempt', 'Risk of follow-up attacks using intelligence gathered from initial breach. Threat actors may have mapped network topology.', 'Cybersecurity', 4, 5, 20, 'Deploy enhanced monitoring on all endpoints. Conduct full penetration test. Reset all service account credentials. Implement zero-trust architecture for sensitive databases.', 'analyzing', 'Pattern analysis of similar breaches shows 60% probability of follow-up attack within 90 days. Recommend immediate implementation of enhanced monitoring and credential rotation across all systems.'),
('Product Liability Litigation', 'Risk of personal injury lawsuits from X500 product defect. Even though no injuries reported, proactive legal preparation needed.', 'Legal', 3, 4, 12, 'Preserve all quality testing records. Engage product liability defense counsel. Document all recall communications and customer responses. Prepare for potential class action.', 'identified', 'Based on similar product recall cases, estimated litigation risk is moderate. Voluntary recall demonstrates good faith. Recommend proactive settlement fund allocation of $5-10M.'),
('Investor Confidence Erosion', 'Multiple concurrent crises risk compounding investor concern. Stock price already down 8% on CFO allegations alone.', 'Financial', 4, 4, 16, 'Schedule investor roadshow within 2 weeks. Prepare detailed Q&A document for analyst calls. Consider accelerating share buyback program. Release positive operational metrics.', 'analyzing', 'Market sentiment analysis shows correlation between crisis count and stock performance. Each additional crisis compounds negative impact by approximately 2-3%. Recommend consolidated positive narrative.'),
('Community Relations Deterioration', 'Plant B community trust at risk following chemical spill. Long-term relationship damage could affect operating permits and expansion plans.', 'Reputation', 3, 3, 9, 'Host community town halls. Establish community monitoring committee. Fund local environmental restoration project. Provide regular air and water quality reports to residents.', 'identified', 'Community sentiment mapping shows 65% negative perception in 5-mile radius. Historical data shows community trust recovery takes 12-18 months with active engagement program.'),
('Regulatory Fine Escalation', 'FDA investigation could expand beyond preliminary inquiry into formal enforcement action.', 'Regulatory', 3, 4, 12, 'Conduct internal compliance audit immediately. Engage former FDA officials as consultants. Prepare voluntary correction plan. Document all compliance improvements.', 'analyzing', 'FDA enforcement patterns suggest 40% of preliminary inquiries escalate to formal action. Voluntary corrective measures reduce escalation probability by approximately 50%.'),
('Supply Chain Single Point of Failure', 'Taiwan supplier disruption reveals over-reliance on single-source components for critical product lines.', 'Operational', 5, 4, 20, 'Qualify minimum 2 alternative suppliers for each critical component. Build strategic inventory buffer of 8 weeks. Develop regional diversification plan for supply base.', 'identified', 'Supply chain vulnerability analysis reveals 12 critical components with single-source dependency. Geographic concentration in earthquake-prone regions increases compound risk.'),
('Employee Morale Decline', 'Multiple crises creating anxiety and uncertainty among workforce. Retention risk increasing especially for key talent.', 'Human Resources', 4, 3, 12, 'Increase frequency of internal communications. Launch employee support program. Conduct pulse surveys. Ensure managers are equipped for difficult conversations. Consider retention bonuses for key roles.', 'identified', 'Employee sentiment data from internal channels shows 30% decline in engagement scores over past month. Exit interview data indicates crisis fatigue as emerging theme.'),
('Brand Reputation Damage', 'Cumulative impact of multiple simultaneous crises on brand equity. Consumer trust metrics declining.', 'Reputation', 4, 5, 20, 'Commission brand health study. Develop brand recovery campaign. Invest in positive storytelling through owned channels. Consider CSR initiative tied to crisis themes.', 'analyzing', 'Brand tracking data shows 15-point decline in Net Promoter Score over 30 days. Competitive analysis shows rival brands gaining consideration among our customer base.'),
('Labor Strike Operational Impact', 'Potential 3,000-worker strike could halt production for weeks. Customer commitments at risk.', 'Operational', 4, 4, 16, 'Prepare contingency workforce plan. Build finished goods inventory. Communicate potential delays to key customers proactively. Accelerate negotiation timeline.', 'identified', 'Strike duration modeling suggests 2-3 week average for similar disputes. Estimated revenue impact of $5M per week of production stoppage.'),
('Misinformation Campaign Escalation', 'Coordinated disinformation could expand to new platforms and topics. Bot network may be state-sponsored.', 'Reputation', 3, 3, 9, 'Engage digital forensics firm to trace bot network. Work with platform trust and safety teams. Prepare fact-check content library. Brief mainstream media on disinformation tactics.', 'analyzing', 'Bot network analysis reveals characteristics consistent with commercial disinformation services. Campaign shows signs of being funded rather than organic. Platform reporting may be most effective countermeasure.'),
('Hurricane Business Interruption', 'Extended facility closures could last 2-4 weeks post-hurricane. Revenue impact across three locations.', 'Natural Disaster', 5, 4, 20, 'Activate business continuity plans. Pre-position recovery equipment. Ensure adequate business interruption insurance coverage. Establish remote work capabilities for office staff.', 'mitigated', 'Historical hurricane recovery data for Gulf Coast industrial facilities shows average 18-day closure. Pre-positioned recovery resources can reduce this by 40%.'),
('Merger Information Leak Investigation', 'SEC investigation risk from premature disclosure of material non-public information about pending acquisition.', 'Legal/Regulatory', 3, 5, 15, 'Conduct internal investigation into leak source. Engage SEC counsel proactively. Review and strengthen information barrier procedures. Assess impact on deal timeline and terms.', 'analyzing', 'SEC enforcement data shows increased scrutiny of pre-announcement leaks. Proactive self-reporting typically results in more favorable outcomes. Recommend engagement with SEC within 48 hours.'),
('Class Action Scope Expansion', 'Risk of class action lawsuit expanding beyond initial data privacy claims to include additional causes of action.', 'Legal', 3, 4, 12, 'Engage top-tier litigation firm. Prepare comprehensive discovery response. Document all data practices and consent mechanisms. Consider early mediation to limit exposure.', 'identified', 'Similar class actions have expanded in 55% of cases. Average settlement range for comparable data privacy cases: $10-50M. Early mediation shows 30% cost reduction.'),
('Cumulative Crisis Fatigue', 'Organization managing 15 simultaneous crises. Risk of errors increasing due to team burnout and resource strain.', 'Organizational', 5, 4, 20, 'Prioritize crises by severity and impact. Bring in external crisis support resources. Implement shift rotations for crisis team. Ensure leadership is modeling self-care.', 'identified', 'Organizational stress indicators at highest levels recorded. Crisis management literature shows error rates increase 300% when teams manage more than 5 simultaneous incidents. Immediate resource augmentation recommended.')
ON CONFLICT DO NOTHING;

-- Talking Points (15 entries)
INSERT INTO talking_points (crisis_id, topic, points, target_audience, tone, spokesperson, ai_generated, status) VALUES
(1, 'Chemical Spill - Community Safety', '1. Safety is our absolute top priority - we activated emergency protocols within minutes.\n2. No injuries have been reported and containment is in place.\n3. We are working hand-in-hand with the EPA and local authorities.\n4. Air and water quality monitoring stations are active and readings are within safe levels.\n5. We will host a community town hall within 48 hours to answer all questions directly.', 'Community Residents', 'Empathetic, Reassuring', 'Sarah Chen', false, 'approved'),
(2, 'Data Breach - Customer Communication', '1. We discovered the breach through our own monitoring and immediately took action.\n2. Affected data is limited to names, emails, and encrypted payment info - no plaintext financial data was exposed.\n3. We have engaged leading cybersecurity experts for a thorough investigation.\n4. Free credit monitoring and identity protection services are available to all affected customers.\n5. We have implemented additional security measures to prevent future incidents.', 'Customers', 'Transparent, Accountable', 'James Wilson', false, 'approved'),
(2, 'Data Breach - Media Talking Points', '1. We take data security extremely seriously and invested $X million in cybersecurity last year.\n2. We detected the breach through proactive monitoring and responded within hours.\n3. We are fully cooperating with law enforcement.\n4. We are going beyond legal requirements in our notification and remediation efforts.\n5. If asked about specifics of the attack, defer to ongoing investigation.', 'Media', 'Professional, Transparent', 'James Wilson', false, 'approved'),
(3, 'Product Recall - Consumer Safety', '1. We discovered this issue through our own quality testing before any injuries occurred.\n2. We made the decision to recall immediately - customer safety comes before profits.\n3. Full refund or replacement available to all affected customers.\n4. The recall process is simple - call our hotline or visit our website.\n5. We are implementing enhanced quality testing to prevent similar issues.', 'Consumers', 'Caring, Action-oriented', 'Maria Garcia', false, 'approved'),
(4, 'Executive Investigation - Investor Talking Points', '1. The Board took immediate action upon learning of the allegations.\n2. An independent investigation is being conducted by external counsel.\n3. The company operations continue normally - this is a personnel matter.\n4. We have strong governance structures in place.\n5. We will share findings as appropriate while respecting the investigative process.', 'Investors, Analysts', 'Professional, Authoritative', 'Robert Johnson', false, 'approved'),
(5, 'Warehouse Fire - Operations Update', '1. All employees were safely evacuated - no injuries.\n2. Fire department responded quickly and fire is fully contained.\n3. We have insurance coverage and are filing claims.\n4. Customer orders will be fulfilled from alternative warehouses.\n5. Cause is under investigation but preliminary signs do not suggest foul play.', 'Customers, Partners', 'Calm, Solution-focused', 'Sarah Chen', false, 'used'),
(6, 'Viral Video - Social Media Response', '1. We take every customer concern seriously regardless of how it comes to our attention.\n2. We have reached out directly to the customer in the video.\n3. Our quality team is investigating the specific incident.\n4. This does not reflect the experience of our millions of satisfied customers.\n5. We encourage anyone with product concerns to contact us directly.', 'Social Media Users', 'Empathetic, Responsive', 'Emily Taylor', true, 'approved'),
(7, 'Labor Strike - Company Position', '1. We respect our employees rights and value their contributions.\n2. We have been negotiating in good faith for six months.\n3. Our proposal includes meaningful wage increases and enhanced benefits.\n4. We remain at the table and committed to reaching an agreement.\n5. We will not discuss specific negotiation details publicly.', 'Media, Public', 'Respectful, Firm', 'Michael Lee', false, 'approved'),
(9, 'FDA Investigation - Regulatory Response', '1. We welcome the opportunity to demonstrate our compliance.\n2. Patient safety is and has always been our paramount concern.\n3. We are fully cooperating with the FDA.\n4. Our products continue to meet all safety and efficacy standards.\n5. We maintain rigorous compliance programs that go beyond minimum requirements.', 'Regulators, Healthcare Providers', 'Cooperative, Confident', 'Daniel Kim', false, 'approved'),
(10, 'Workplace Safety - OSHA Response', '1. We deeply regret this incident and our thoughts are with the affected employee.\n2. The employee is receiving full medical care and is expected to recover.\n3. We immediately halted operations for a comprehensive safety review.\n4. We have reported to OSHA and are fully cooperating.\n5. Additional safety measures have been implemented to prevent recurrence.', 'OSHA, Employees, Media', 'Concerned, Responsible', 'Amanda White', false, 'used'),
(11, 'Misinformation - Factual Response', '1. The claims being spread online about our products are categorically false.\n2. Our products meet or exceed all regulatory requirements.\n3. We have commissioned independent laboratory testing - results will be public.\n4. We are working with platforms to address the coordinated spread of false information.\n5. Consumers can verify our product information at [website].', 'Public, Media', 'Firm, Factual', 'Rachel Davis', true, 'approved'),
(12, 'Hurricane Response - Employee Safety', '1. Employee safety is our first and only priority right now.\n2. All non-essential operations suspended at Gulf Coast facilities.\n3. Employees should follow local authority evacuation orders.\n4. Emergency financial assistance available for affected employees.\n5. Do not return to facilities until official all-clear is issued.', 'Employees', 'Urgent, Caring', 'Chris Anderson', false, 'approved'),
(1, 'Chemical Spill - Environmental Impact', '1. Containment has been successful - the spill has not reached any waterways.\n2. Environmental monitoring is ongoing with results shared publicly.\n3. We have engaged environmental remediation experts.\n4. Full cleanup and restoration is our commitment.\n5. We will fund independent environmental assessment by a community-chosen firm.', 'Environmental Groups, Regulators', 'Responsible, Proactive', 'Sarah Chen', true, 'draft'),
(4, 'Executive Investigation - Employee Communication', '1. I want to address the news reports directly - you deserve to hear from leadership first.\n2. The Board has taken appropriate action and an investigation is underway.\n3. This does not change your jobs, your teams, or our mission.\n4. Please direct any media inquiries to our PR team.\n5. We will share what we can as the process unfolds. Your focus should remain on serving our customers.', 'Employees', 'Supportive, Direct', 'CEO', false, 'approved'),
(14, 'Data Privacy Lawsuit - Public Position', '1. We believe the allegations are without merit.\n2. We maintain robust data privacy practices.\n3. We comply with all applicable data protection regulations.\n4. We will vigorously defend our position through proper legal channels.\n5. We remain committed to transparency in our data practices.', 'Public, Media', 'Confident, Measured', 'Thomas Martinez', false, 'approved')
ON CONFLICT DO NOTHING;

-- Post-Crisis Analyses (15 entries)
INSERT INTO post_crisis_analyses (crisis_id, title, summary, what_went_well, what_went_wrong, recommendations, metrics, ai_analysis, status) VALUES
(10, 'Workplace Safety Incident Analysis - Chicago Plant A', 'Analysis of the manufacturing line accident that resulted in one employee injury. The incident occurred during a routine maintenance operation when a safety guard was temporarily removed.', 'Emergency response was swift - medical team on site in 3 minutes. OSHA notification completed within required timeframe. Employee received immediate medical attention. Communication to workforce was transparent and timely.', 'Safety guard lockout/tagout procedure was not followed. Pre-shift safety checklist was incomplete. Supervisor oversight during maintenance was insufficient. Near-miss reporting system had flagged similar risks 2 months prior without corrective action.', '1. Implement mandatory buddy system for all maintenance operations.\n2. Install electronic lockout/tagout verification system.\n3. Require supervisor sign-off on all pre-shift safety checklists.\n4. Create escalation protocol for near-miss reports.\n5. Conduct quarterly safety culture assessments.', 'Response time: 3 minutes. OSHA notification: Within 8 hours. Employee recovery: Expected full recovery in 6 weeks. Days since previous incident before this: 247. Safety training hours per employee: 24/year.', 'Root cause analysis reveals systemic gap between safety policy and practice. The near-miss reporting data from 2 months prior should have triggered preventive action. This represents a process failure rather than individual failure. Recommend focusing corrective actions on systemic improvements rather than individual accountability.', 'final'),
(1, 'Chemical Spill Response - Preliminary Analysis', 'Preliminary analysis of the Plant B chemical spill response. Full analysis pending completion of environmental remediation.', 'Emergency response team activated within 8 minutes. Containment prevented spread to waterways. EPA notification completed within regulatory timeframe. Press conference held within 4 hours of incident. No injuries reported.', 'Tank monitoring systems did not provide adequate advance warning. Emergency response equipment staging was suboptimal - 10 minute delay in barrier deployment. Initial community notification was delayed by 45 minutes. Internal communication chain had gaps.', '1. Upgrade tank monitoring to real-time pressure and integrity sensors.\n2. Pre-position emergency response equipment closer to high-risk areas.\n3. Implement automated community notification system.\n4. Create dedicated crisis communication channel for internal coordination.\n5. Conduct quarterly emergency drills at all chemical storage facilities.', 'Detection to response: 8 minutes. Containment completion: 45 minutes. EPA notification: 25 minutes. Media response: 4 hours. Community notification: 1 hour 45 minutes. Estimated remediation cost: $500K-$1M.', 'Response was generally effective but several timing gaps identified. The 45-minute community notification delay is the most significant finding - regulatory best practice is 30 minutes. Tank infrastructure age (25+ years) is the fundamental risk factor requiring capital investment.', 'draft'),
(2, 'Data Breach Response Assessment - In Progress', 'Assessment of the cybersecurity incident response and communication strategy. Investigation still ongoing.', 'Detection through internal monitoring rather than external discovery. Swift credential revocation (45 minutes from detection). Customer notification exceeded regulatory requirements. Credit monitoring offer well-received by customers.', 'Vendor credential management was inadequate. Database access controls were too permissive. Initial scope assessment underestimated affected records. Crisis hotline was understaffed for call volume.', '1. Implement privileged access management (PAM) for all vendor accounts.\n2. Apply principle of least privilege to all database access.\n3. Increase crisis hotline surge capacity.\n4. Conduct monthly vendor security audits.\n5. Implement data loss prevention (DLP) tools.', 'Detection to containment: 45 minutes. Records affected: 50,000. Customer notification: Within 24 hours. Hotline calls handled: 847 in first 6 hours. Average wait time: 4 minutes. Credit monitoring enrollment: 62% of affected customers.', 'The breach vector (compromised vendor credentials) is the #1 attack vector in 2026. The company detection time of 45 minutes is significantly better than industry average of 197 days. However, the permissive database access controls amplified the impact. Recommend zero-trust architecture implementation.', 'draft'),
(3, 'Product Recall X500 - Preliminary Review', 'Review of the voluntary recall process for Model X500 battery defect. Recall still in progress.', 'Defect identified through internal testing before any customer injuries. Voluntary recall decision made within 48 hours of discovery. Clear and simple return process for customers. Retail partner coordination was efficient.', 'Quality testing interval may have been too long - defect could have been caught earlier. Initial production quality controls did not detect the issue. Customer communication could have been more personalized. Website crashed under traffic load during announcement.', '1. Increase frequency of post-production quality testing.\n2. Add battery stress testing to production line QC.\n3. Scale web infrastructure for crisis traffic.\n4. Develop personalized customer communication templates.\n5. Create dedicated recall management team.', 'Units affected: 25,000. Return rate: 45% (ongoing). Customer complaints pre-recall: 0. Time from discovery to recall announcement: 48 hours. CPSC notification: Within 24 hours. Estimated total cost: $15-20M.', 'The proactive voluntary recall is a textbook best practice and will likely reduce litigation risk significantly. The 48-hour decision timeline is commendable. Website infrastructure failure during announcement is a recurring issue across industries - recommend CDN and load balancing for crisis pages.', 'draft'),
(5, 'Warehouse Fire - Insurance and Recovery Analysis', 'Analysis of the Newark warehouse fire response, insurance claims process, and supply chain recovery.', 'Zero injuries due to effective evacuation. Fire department response coordination was excellent. Insurance claim filed promptly. Alternative fulfillment arrangements implemented within 24 hours.', 'Fire suppression system in Warehouse 7 was due for maintenance. Inventory was not adequately distributed across multiple locations. Backup fulfillment capacity was barely sufficient.', '1. Implement strict fire suppression system maintenance schedule.\n2. Distribute inventory across minimum 3 warehouse locations.\n3. Build 20% excess fulfillment capacity across network.\n4. Install advanced fire detection systems.\n5. Review and update business continuity plans annually.', 'Evacuation time: 4 minutes. Fire department response: 7 minutes. Inventory loss: $2M. Insurance claim filed: Same day. Alternative fulfillment active: 24 hours. Customer order delays: Average 2 days.', 'Fire suppression maintenance gap is the critical finding. Industry data shows facilities with overdue maintenance have 5x higher loss severity. The rapid alternative fulfillment activation demonstrates good business continuity planning. Recommend geographic diversification of inventory.', 'draft'),
(6, 'Viral Social Media Incident - Digital Response Review', 'Review of social media crisis response to viral product complaint video.', 'Rapid detection of viral content (within 1 hour of significant spread). Direct outreach to affected customer was well-received. Social media response team maintained professional tone throughout. Negative trend stabilized within 48 hours.', 'Initial response template felt generic. Did not have pre-approved content for this scenario type. Competitor brands capitalized on the situation with comparative messaging. Internal approval chain slowed response by 2 hours.', '1. Develop pre-approved response templates for common viral scenarios.\n2. Reduce social media crisis approval chain to 2 levels.\n3. Monitor competitor activity during social media crises.\n4. Train customer service team on social media escalation.\n5. Build library of authentic customer success stories for counter-narrative.', 'Time to detection: 1 hour. Time to first response: 3 hours. Peak negative mentions: 15,000/hour. Sentiment recovery time: 48 hours. Video views: 2.1M. Follow-up positive engagement: 45% increase after customer resolution.', 'The 3-hour response time is at the upper limit of acceptable for social media crises. The customer resolution story became a positive narrative - this pattern should be replicated. Recommend investing in AI-powered social listening tools for faster detection.', 'final'),
(7, 'Labor Strike Negotiation - Communication Analysis', 'Analysis of communication strategy during labor dispute and strike negotiations.', 'Maintained respectful tone throughout public communications. Did not engage in public blame game. Negotiation team was well-prepared. Employee communication was consistent and timely.', 'Public statement timing was reactive rather than proactive. Social media discussion was largely dominated by union messaging. Did not adequately communicate company proposal benefits to broader public. Internal communication to non-union employees was insufficient.', '1. Develop proactive communication timeline for labor disputes.\n2. Create social media content strategy for labor negotiations.\n3. Prepare public-friendly summaries of company proposals.\n4. Include non-union employee communication in crisis plan.\n5. Engage community stakeholders as neutral third parties.', 'Duration of negotiations: 6 months. Strike notice: 7 days. Company proposals presented: 3. Media mentions: 450+. Social media sentiment: 60% pro-union, 25% neutral, 15% pro-company. Employee communications sent: 12.', 'Communication was appropriate but not strategic enough. The 60/25/15 sentiment split suggests the company narrative was not effectively reaching the public. In future labor disputes, recommend earlier proactive communication to establish the company as a fair employer.', 'draft'),
(9, 'FDA Investigation Communication Strategy Review', 'Review of communication approach during FDA preliminary inquiry into pharmaceutical division.', 'Immediate cooperation stance with FDA. Proactive document submission. Healthcare provider communication was professional and reassuring. Did not create unnecessary public alarm.', 'Initial internal communication created some employee anxiety. Media statement was perceived as too defensive by some analysts. Did not adequately prepare for leaked investigation details. Investor communication was delayed.', '1. Develop regulatory investigation playbook with pre-drafted communications.\n2. Train employees on regulatory investigation protocols annually.\n3. Prepare tiered media statements from acknowledgment to resolution.\n4. Establish rapid investor communication protocol for regulatory events.\n5. Engage former regulatory officials as advisors proactively.', 'FDA notification to public awareness: 3 days (leaked). Investor communication delay: 48 hours. Media inquiries: 75+. Healthcare provider inquiries: 120. Stock impact: -3.5% on news. Employee questions to HR: 200+.', 'The 48-hour investor communication delay is the most significant gap. In regulated industries, investor expectations for rapid disclosure are higher. The cooperation stance with FDA was strategically correct and should reduce investigation duration by an estimated 30%.', 'draft'),
(11, 'Misinformation Campaign Response Analysis', 'Analysis of response to coordinated disinformation campaign targeting product ingredients.', 'Quick identification of bot network involvement. Effective coordination with social media platform trust teams. Independent lab testing was a strong credibility move. Brand advocates emerged organically.', 'Took 24 hours to publish definitive fact-check content. Did not anticipate cross-platform spread. Initial response focused too much on denial rather than proactive proof. Legal review slowed content approval.', '1. Pre-prepare fact-check content library for common false claims.\n2. Develop cross-platform monitoring and response capability.\n3. Lead with proof rather than denial in misinformation responses.\n4. Create expedited legal review process for crisis content.\n5. Build and maintain a brand advocate network for rapid amplification.', 'Bot accounts identified: 2,300. False claim impressions: 12M. Platform removals: 1,800 accounts. Fact-check engagement: 500K. Time to trend reversal: 72 hours. Independent lab results published: Day 3.', 'Misinformation campaigns are becoming more sophisticated. The 72-hour trend reversal is acceptable but could be improved to 48 hours with pre-prepared content. The commercial nature of the bot network suggests this was a paid attack - recommend investigation into potential competitors or adversaries.', 'final'),
(12, 'Hurricane Preparedness Execution Review', 'Review of hurricane emergency response plan execution for Gulf Coast facilities.', 'All employees accounted for within 3 hours. Evacuation plans executed smoothly. Business continuity plans activated on schedule. Employee emergency assistance program received positive feedback.', 'Two remote locations had communication gaps during evacuation. Some employees did not receive SMS alerts due to outdated contact information. Pre-positioned supplies at one location were insufficient. Post-storm facility access assessment was delayed.', '1. Install satellite communication backup at all facilities.\n2. Conduct quarterly employee contact information verification.\n3. Increase pre-positioned emergency supply levels by 50%.\n4. Develop drone-based facility assessment capability for post-storm evaluation.\n5. Create mutual aid agreements with facilities in non-affected regions.', 'Employees evacuated: 5,200. Facilities secured: 3. Communication gaps: 2 locations. Employee assistance applications: 340. Business continuity activation time: 4 hours. Estimated property protection savings: $3M.', 'Emergency preparedness plan was 85% effective. The 15% gap is primarily communication infrastructure related. Satellite communication backup is the highest priority improvement. Employee contact database currency of 85% needs to reach 98% minimum for effective emergency notification.', 'draft'),
(13, 'Merger Leak - Information Security Review', 'Analysis of information security breach that led to premature disclosure of acquisition discussions.', 'Legal team responded rapidly to assess SEC implications. Holding statement was appropriate and did not confirm or deny. Market communication maintained regulatory compliance.', 'Information barrier procedures were insufficient. Leak source not immediately identified. Some employees discussed the reports on social media. SEC proactive engagement was delayed by 24 hours.', '1. Strengthen information barrier procedures with digital access controls.\n2. Implement deal-specific communication protocols.\n3. Train employees on MNPI handling annually.\n4. Establish immediate SEC notification protocol for potential leaks.\n5. Review and restrict access to deal information to essential personnel only.', 'Time from leak to market awareness: 4 hours. Stock price movement: +12%. SEC notification: 48 hours post-leak. Personnel with deal access: 23. Social media employee posts: 7. Media inquiries: 95.', 'The leak represents a significant compliance failure. The 23 people with deal access is higher than best practice (typically 10-15 for deals of this size). Employee social media activity during the event suggests inadequate MNPI training. SEC engagement delay increases regulatory risk.', 'draft'),
(14, 'Data Privacy Lawsuit - Communication Strategy Assessment', 'Assessment of communication approach for class action data privacy litigation.', 'Legal communication was measured and appropriate. Did not make any admissions in public statements. Customer communication maintained confidence in data practices.', 'Reactive rather than proactive public positioning. Did not effectively communicate existing privacy protections. Some customer inquiries went unanswered for 48+ hours. Privacy policy page on website was not updated to address concerns.', '1. Develop proactive privacy communication campaign.\n2. Create dedicated privacy FAQ page on website.\n3. Ensure customer inquiry response within 4 hours during crisis.\n4. Publish annual transparency report on data practices.\n5. Consider appointing customer-facing Chief Privacy Officer.', 'Customer inquiries: 1,200. Average response time: 36 hours. Media mentions: 180. Customer churn attributed to incident: 2.3%. Social media sentiment: 70% negative. Privacy page visits: 45,000 (10x normal).', 'The 2.3% customer churn is lower than average for data privacy incidents (typically 3-5%), suggesting the overall approach was effective despite gaps. The 36-hour average response time needs significant improvement. Proactive privacy communication would have reduced inquiry volume by an estimated 40%.', 'draft'),
(15, 'Environmental Protest - Community Engagement Review', 'Review of community engagement approach during environmental activist protests.', 'Did not escalate confrontation. Community forum invitation was well-received. Maintained open dialogue throughout. Security handled protester interactions professionally.', 'Initial response was slow (12 hours to first public statement). Did not engage environmental group leadership early enough. Internal talking points were not aligned across departments. Media coverage was largely sympathetic to protesters.', '1. Develop environmental stakeholder engagement program.\n2. Create rapid response protocol for activist events.\n3. Align all departmental talking points through central crisis team.\n4. Establish ongoing dialogue with environmental advocacy groups.\n5. Invest in visible environmental sustainability initiatives.', 'Protester count: Peak 200. Duration: 3 days. Media stories: 25. Community forum attendance: 150. Social media sentiment shift post-forum: 20% improvement. Employee volunteer sign-ups for community cleanup: 75.', 'The community forum was the turning point - 20% sentiment improvement demonstrates the power of face-to-face engagement. The 12-hour initial response delay allowed the narrative to be established by protesters. Environmental sustainability investments would provide ongoing reputation protection.', 'final'),
(1, 'Chemical Spill - 72-Hour Review', 'Comprehensive 72-hour review of the chemical spill response at Plant B facility.', 'Containment was effective - no environmental spread beyond initial perimeter. Multi-agency coordination (EPA, local fire, hazmat) worked well. Public communication cadence was appropriate (4 updates in 72 hours). Community town hall was well-attended and productive.', 'Initial spill volume was underestimated by 30%. Environmental monitoring data sharing with community was not real-time. Clean-up contractor mobilization took 18 hours vs. target of 12 hours. Employee communication to off-shift workers was delayed.', '1. Improve spill estimation protocols and training.\n2. Implement real-time environmental data dashboard accessible to community.\n3. Pre-contract emergency cleanup services with guaranteed response times.\n4. Create off-shift employee emergency notification system.\n5. Establish community environmental advisory panel.', 'Containment time: 45 minutes. Area affected: 0.5 acres. Cleanup progress at 72 hours: 60%. Community complaints: 34. EPA violations cited: 0. Air quality readings: Within limits. Water quality: No contamination detected.', 'The zero EPA violations is the most significant positive outcome. The spill volume underestimation (30%) could have had serious consequences if actual volume had been larger. Real-time community data sharing would significantly improve trust and reduce complaint volume. Overall response grade: B+.', 'draft')
ON CONFLICT DO NOTHING;
