import {
  getCrisisIncidents, getCrisisIncident, createCrisisIncident, updateCrisisIncident, deleteCrisisIncident,
  getMediaMonitoring, getMediaMonitoringItem, createMediaMonitoring, updateMediaMonitoring, deleteMediaMonitoring,
  getStakeholders, getStakeholder, createStakeholder, updateStakeholder, deleteStakeholder,
  getResponseTemplates, getResponseTemplate, createResponseTemplate, updateResponseTemplate, deleteResponseTemplate,
  getPressReleases, getPressRelease, createPressRelease, updatePressRelease, deletePressRelease, generatePressRelease,
  getSocialMedia, getSocialMediaItem, createSocialMedia, updateSocialMedia, deleteSocialMedia, generateSocialMedia,
  getSentimentAnalyses, getSentimentAnalysis, createSentimentAnalysis, updateSentimentAnalysis, deleteSentimentAnalysis, analyzeSentiment,
  getCrisisSimulations, getCrisisSimulation, createCrisisSimulation, updateCrisisSimulation, deleteCrisisSimulation,
  getCommunicationLogs, getCommunicationLog, createCommunicationLog, updateCommunicationLog, deleteCommunicationLog,
  getTeamMembers, getTeamMember, createTeamMember, updateTeamMember, deleteTeamMember,
  getIncidentTimelines, getIncidentTimeline, createIncidentTimeline, updateIncidentTimeline, deleteIncidentTimeline,
  getRiskAssessments, getRiskAssessment, createRiskAssessment, updateRiskAssessment, deleteRiskAssessment, generateRiskAssessment,
  getTalkingPoints, getTalkingPoint, createTalkingPoint, updateTalkingPoint, deleteTalkingPoint, generateTalkingPoints,
  getPostCrisisAnalyses, getPostCrisisAnalysis, createPostCrisisAnalysis, updatePostCrisisAnalysis, deletePostCrisisAnalysis, generatePostCrisisAnalysis,
} from '../services/api';

export const crisisIncidentsConfig = {
  title: 'Crisis Incidents',
  apiGetAll: getCrisisIncidents,
  apiGetOne: getCrisisIncident,
  apiCreate: createCrisisIncident,
  apiUpdate: updateCrisisIncident,
  apiDelete: deleteCrisisIncident,
  columns: [
    { key: 'title', label: 'Title' },
    { key: 'severity', label: 'Severity', badge: true },
    { key: 'status', label: 'Status', badge: true },
    { key: 'category', label: 'Category' },
    { key: 'location', label: 'Location' },
    { key: 'lead_responder', label: 'Lead' },
  ],
  fields: [
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
    { key: 'status', label: 'Status', type: 'select', options: ['active', 'monitoring', 'resolved', 'closed'] },
    { key: 'category', label: 'Category', type: 'text' },
    { key: 'location', label: 'Location', type: 'text' },
    { key: 'affected_stakeholders', label: 'Affected Stakeholders', type: 'textarea' },
    { key: 'lead_responder', label: 'Lead Responder', type: 'text' },
  ],
};

export const mediaMonitoringConfig = {
  title: 'Media Monitoring',
  apiGetAll: getMediaMonitoring,
  apiGetOne: getMediaMonitoringItem,
  apiCreate: createMediaMonitoring,
  apiUpdate: updateMediaMonitoring,
  apiDelete: deleteMediaMonitoring,
  columns: [
    { key: 'title', label: 'Title' },
    { key: 'source', label: 'Source' },
    { key: 'platform', label: 'Platform' },
    { key: 'sentiment', label: 'Sentiment', badge: true },
    { key: 'reach', label: 'Reach' },
  ],
  fields: [
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'source', label: 'Source', type: 'text' },
    { key: 'url', label: 'URL', type: 'text' },
    { key: 'sentiment', label: 'Sentiment', type: 'select', options: ['positive', 'negative', 'neutral', 'mixed'] },
    { key: 'reach', label: 'Reach', type: 'number' },
    { key: 'platform', label: 'Platform', type: 'select', options: ['twitter', 'facebook', 'linkedin', 'news', 'tv', 'radio', 'blog', 'reddit'] },
    { key: 'summary', label: 'Summary', type: 'textarea' },
    { key: 'published_at', label: 'Published At', type: 'datetime-local' },
  ],
};

export const stakeholdersConfig = {
  title: 'Stakeholders',
  apiGetAll: getStakeholders,
  apiGetOne: getStakeholder,
  apiCreate: createStakeholder,
  apiUpdate: updateStakeholder,
  apiDelete: deleteStakeholder,
  columns: [
    { key: 'name', label: 'Name' },
    { key: 'organization', label: 'Organization' },
    { key: 'role', label: 'Role' },
    { key: 'priority', label: 'Priority', badge: true },
    { key: 'email', label: 'Email' },
  ],
  fields: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'organization', label: 'Organization', type: 'text' },
    { key: 'role', label: 'Role', type: 'text' },
    { key: 'email', label: 'Email', type: 'email' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'priority', label: 'Priority', type: 'select', options: ['primary', 'secondary', 'tertiary'] },
    { key: 'relationship', label: 'Relationship', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
};

export const responseTemplatesConfig = {
  title: 'Response Templates',
  apiGetAll: getResponseTemplates,
  apiGetOne: getResponseTemplate,
  apiCreate: createResponseTemplate,
  apiUpdate: updateResponseTemplate,
  apiDelete: deleteResponseTemplate,
  columns: [
    { key: 'name', label: 'Name' },
    { key: 'category', label: 'Category' },
    { key: 'use_case', label: 'Use Case' },
    { key: 'tone', label: 'Tone', badge: true },
  ],
  fields: [
    { key: 'name', label: 'Template Name', type: 'text', required: true },
    { key: 'category', label: 'Category', type: 'text' },
    { key: 'template_text', label: 'Template Text', type: 'textarea', required: true },
    { key: 'variables', label: 'Variables (comma-separated)', type: 'text' },
    { key: 'use_case', label: 'Use Case', type: 'text' },
    { key: 'tone', label: 'Tone', type: 'select', options: ['empathetic', 'factual', 'reassuring', 'urgent', 'formal', 'apologetic'] },
  ],
};

export const pressReleasesConfig = {
  title: 'Press Releases',
  isAI: true,
  apiGetAll: getPressReleases,
  apiGetOne: getPressRelease,
  apiCreate: createPressRelease,
  apiUpdate: updatePressRelease,
  apiDelete: deletePressRelease,
  aiGenerate: generatePressRelease,
  aiLabel: 'Generate Press Release',
  aiFields: [
    { key: 'crisis_title', label: 'Crisis Title', type: 'text', required: true },
    { key: 'crisis_details', label: 'Crisis Details', type: 'textarea', required: true },
    { key: 'company_name', label: 'Company Name', type: 'text' },
    { key: 'spokesperson', label: 'Spokesperson', type: 'text' },
    { key: 'tone', label: 'Tone', type: 'select', options: ['empathetic', 'factual', 'reassuring', 'urgent'] },
  ],
  aiResponseField: 'content',
  columns: [
    { key: 'title', label: 'Title' },
    { key: 'status', label: 'Status', badge: true },
    { key: 'target_audience', label: 'Audience' },
    { key: 'ai_generated', label: 'AI', boolean: true },
  ],
  fields: [
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'content', label: 'Content', type: 'textarea' },
    { key: 'crisis_id', label: 'Crisis ID', type: 'number' },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'review', 'approved', 'published'] },
    { key: 'target_audience', label: 'Target Audience', type: 'text' },
    { key: 'ai_generated', label: 'AI Generated', type: 'checkbox' },
  ],
};

export const socialMediaConfig = {
  title: 'Social Media Responses',
  isAI: true,
  apiGetAll: getSocialMedia,
  apiGetOne: getSocialMediaItem,
  apiCreate: createSocialMedia,
  apiUpdate: updateSocialMedia,
  apiDelete: deleteSocialMedia,
  aiGenerate: generateSocialMedia,
  aiLabel: 'Generate Social Response',
  aiFields: [
    { key: 'platform', label: 'Platform', type: 'select', options: ['twitter', 'facebook', 'linkedin', 'instagram'], required: true },
    { key: 'crisis_context', label: 'Crisis Context', type: 'textarea', required: true },
    { key: 'tone', label: 'Tone', type: 'select', options: ['empathetic', 'factual', 'reassuring', 'urgent'] },
    { key: 'key_message', label: 'Key Message', type: 'text' },
  ],
  aiResponseField: 'message',
  columns: [
    { key: 'platform', label: 'Platform', badge: true },
    { key: 'message', label: 'Message' },
    { key: 'status', label: 'Status', badge: true },
    { key: 'tone', label: 'Tone' },
    { key: 'ai_generated', label: 'AI', boolean: true },
  ],
  fields: [
    { key: 'platform', label: 'Platform', type: 'select', options: ['twitter', 'facebook', 'linkedin', 'instagram'] },
    { key: 'message', label: 'Message', type: 'textarea', required: true },
    { key: 'crisis_id', label: 'Crisis ID', type: 'number' },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'scheduled', 'posted'] },
    { key: 'tone', label: 'Tone', type: 'select', options: ['empathetic', 'factual', 'reassuring', 'urgent'] },
    { key: 'character_count', label: 'Character Count', type: 'number' },
    { key: 'ai_generated', label: 'AI Generated', type: 'checkbox' },
  ],
};

export const sentimentAnalysisConfig = {
  title: 'Sentiment Analysis',
  isAI: true,
  apiGetAll: getSentimentAnalyses,
  apiGetOne: getSentimentAnalysis,
  apiCreate: createSentimentAnalysis,
  apiUpdate: updateSentimentAnalysis,
  apiDelete: deleteSentimentAnalysis,
  aiGenerate: analyzeSentiment,
  aiLabel: 'Analyze Sentiment',
  aiFields: [
    { key: 'text_input', label: 'Text to Analyze', type: 'textarea', required: true },
    { key: 'source', label: 'Source', type: 'text' },
  ],
  aiResponseField: 'ai_analysis',
  columns: [
    { key: 'text_input', label: 'Text' },
    { key: 'sentiment_label', label: 'Sentiment', badge: true },
    { key: 'sentiment_score', label: 'Score' },
    { key: 'source', label: 'Source' },
  ],
  fields: [
    { key: 'text_input', label: 'Text Input', type: 'textarea', required: true },
    { key: 'sentiment_score', label: 'Sentiment Score (-1 to 1)', type: 'number' },
    { key: 'sentiment_label', label: 'Sentiment Label', type: 'select', options: ['positive', 'negative', 'neutral', 'mixed'] },
    { key: 'key_phrases', label: 'Key Phrases', type: 'textarea' },
    { key: 'emotions', label: 'Emotions', type: 'textarea' },
    { key: 'source', label: 'Source', type: 'text' },
    { key: 'ai_analysis', label: 'AI Analysis', type: 'textarea' },
  ],
};

export const crisisSimulationsConfig = {
  title: 'Crisis Simulations',
  apiGetAll: getCrisisSimulations,
  apiGetOne: getCrisisSimulation,
  apiCreate: createCrisisSimulation,
  apiUpdate: updateCrisisSimulation,
  apiDelete: deleteCrisisSimulation,
  columns: [
    { key: 'scenario_name', label: 'Scenario' },
    { key: 'severity', label: 'Severity', badge: true },
    { key: 'status', label: 'Status', badge: true },
    { key: 'scheduled_date', label: 'Scheduled', date: true },
  ],
  fields: [
    { key: 'scenario_name', label: 'Scenario Name', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
    { key: 'objectives', label: 'Objectives', type: 'textarea' },
    { key: 'participants', label: 'Participants', type: 'textarea' },
    { key: 'status', label: 'Status', type: 'select', options: ['planned', 'in_progress', 'completed'] },
    { key: 'results', label: 'Results', type: 'textarea' },
    { key: 'lessons_learned', label: 'Lessons Learned', type: 'textarea' },
    { key: 'scheduled_date', label: 'Scheduled Date', type: 'datetime-local' },
  ],
};

export const communicationLogsConfig = {
  title: 'Communication Logs',
  apiGetAll: getCommunicationLogs,
  apiGetOne: getCommunicationLog,
  apiCreate: createCommunicationLog,
  apiUpdate: updateCommunicationLog,
  apiDelete: deleteCommunicationLog,
  columns: [
    { key: 'channel', label: 'Channel' },
    { key: 'sender', label: 'Sender' },
    { key: 'recipient', label: 'Recipient' },
    { key: 'direction', label: 'Direction', badge: true },
    { key: 'status', label: 'Status', badge: true },
  ],
  fields: [
    { key: 'crisis_id', label: 'Crisis ID', type: 'number' },
    { key: 'channel', label: 'Channel', type: 'select', options: ['email', 'phone', 'slack', 'teams', 'press', 'social_media', 'in_person'] },
    { key: 'sender', label: 'Sender', type: 'text', required: true },
    { key: 'recipient', label: 'Recipient', type: 'text', required: true },
    { key: 'message', label: 'Message', type: 'textarea', required: true },
    { key: 'direction', label: 'Direction', type: 'select', options: ['inbound', 'outbound'] },
    { key: 'status', label: 'Status', type: 'select', options: ['sent', 'delivered', 'read', 'pending', 'failed'] },
  ],
};

export const teamMembersConfig = {
  title: 'Team Management',
  apiGetAll: getTeamMembers,
  apiGetOne: getTeamMember,
  apiCreate: createTeamMember,
  apiUpdate: updateTeamMember,
  apiDelete: deleteTeamMember,
  columns: [
    { key: 'name', label: 'Name' },
    { key: 'role', label: 'Role' },
    { key: 'department', label: 'Department' },
    { key: 'availability', label: 'Availability', badge: true },
    { key: 'email', label: 'Email' },
  ],
  fields: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'email', label: 'Email', type: 'email' },
    { key: 'role', label: 'Role', type: 'text' },
    { key: 'department', label: 'Department', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'availability', label: 'Availability', type: 'select', options: ['available', 'busy', 'offline'] },
    { key: 'skills', label: 'Skills', type: 'textarea' },
    { key: 'assigned_crisis_id', label: 'Assigned Crisis ID', type: 'number' },
  ],
};

export const incidentTimelinesConfig = {
  title: 'Incident Timelines',
  apiGetAll: getIncidentTimelines,
  apiGetOne: getIncidentTimeline,
  apiCreate: createIncidentTimeline,
  apiUpdate: updateIncidentTimeline,
  apiDelete: deleteIncidentTimeline,
  columns: [
    { key: 'event_title', label: 'Event' },
    { key: 'event_type', label: 'Type' },
    { key: 'reported_by', label: 'Reported By' },
    { key: 'impact_level', label: 'Impact', badge: true },
    { key: 'timestamp', label: 'Timestamp', date: true },
  ],
  fields: [
    { key: 'crisis_id', label: 'Crisis ID', type: 'number' },
    { key: 'event_title', label: 'Event Title', type: 'text', required: true },
    { key: 'event_description', label: 'Event Description', type: 'textarea' },
    { key: 'event_type', label: 'Event Type', type: 'select', options: ['detection', 'escalation', 'response', 'communication', 'resolution', 'update'] },
    { key: 'timestamp', label: 'Timestamp', type: 'datetime-local' },
    { key: 'reported_by', label: 'Reported By', type: 'text' },
    { key: 'impact_level', label: 'Impact Level', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
  ],
};

export const riskAssessmentsConfig = {
  title: 'Risk Assessments',
  isAI: true,
  apiGetAll: getRiskAssessments,
  apiGetOne: getRiskAssessment,
  apiCreate: createRiskAssessment,
  apiUpdate: updateRiskAssessment,
  apiDelete: deleteRiskAssessment,
  aiGenerate: generateRiskAssessment,
  aiLabel: 'AI Risk Assessment',
  aiFields: [
    { key: 'scenario', label: 'Risk Scenario', type: 'textarea', required: true },
    { key: 'industry', label: 'Industry', type: 'text' },
    { key: 'company_context', label: 'Company Context', type: 'textarea' },
  ],
  aiResponseField: 'ai_analysis',
  columns: [
    { key: 'title', label: 'Title' },
    { key: 'category', label: 'Category' },
    { key: 'risk_score', label: 'Risk Score' },
    { key: 'status', label: 'Status', badge: true },
    { key: 'likelihood', label: 'Likelihood' },
    { key: 'impact', label: 'Impact' },
  ],
  fields: [
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'category', label: 'Category', type: 'select', options: ['reputational', 'operational', 'financial', 'legal', 'environmental', 'cybersecurity', 'health_safety'] },
    { key: 'likelihood', label: 'Likelihood (1-5)', type: 'number' },
    { key: 'impact', label: 'Impact (1-5)', type: 'number' },
    { key: 'risk_score', label: 'Risk Score', type: 'number' },
    { key: 'mitigation_strategy', label: 'Mitigation Strategy', type: 'textarea' },
    { key: 'status', label: 'Status', type: 'select', options: ['identified', 'analyzing', 'mitigated', 'accepted'] },
    { key: 'ai_analysis', label: 'AI Analysis', type: 'textarea' },
  ],
};

export const talkingPointsConfig = {
  title: 'Talking Points',
  isAI: true,
  apiGetAll: getTalkingPoints,
  apiGetOne: getTalkingPoint,
  apiCreate: createTalkingPoint,
  apiUpdate: updateTalkingPoint,
  apiDelete: deleteTalkingPoint,
  aiGenerate: generateTalkingPoints,
  aiLabel: 'Generate Talking Points',
  aiFields: [
    { key: 'topic', label: 'Topic / Crisis', type: 'text', required: true },
    { key: 'context', label: 'Context & Details', type: 'textarea', required: true },
    { key: 'target_audience', label: 'Target Audience', type: 'select', options: ['media', 'employees', 'customers', 'investors', 'regulators', 'public'] },
    { key: 'tone', label: 'Tone', type: 'select', options: ['empathetic', 'factual', 'reassuring', 'urgent', 'apologetic'] },
  ],
  aiResponseField: 'points',
  columns: [
    { key: 'topic', label: 'Topic' },
    { key: 'target_audience', label: 'Audience' },
    { key: 'tone', label: 'Tone' },
    { key: 'spokesperson', label: 'Spokesperson' },
    { key: 'status', label: 'Status', badge: true },
    { key: 'ai_generated', label: 'AI', boolean: true },
  ],
  fields: [
    { key: 'crisis_id', label: 'Crisis ID', type: 'number' },
    { key: 'topic', label: 'Topic', type: 'text', required: true },
    { key: 'points', label: 'Talking Points', type: 'textarea', required: true },
    { key: 'target_audience', label: 'Target Audience', type: 'select', options: ['media', 'employees', 'customers', 'investors', 'regulators', 'public'] },
    { key: 'tone', label: 'Tone', type: 'select', options: ['empathetic', 'factual', 'reassuring', 'urgent', 'apologetic'] },
    { key: 'spokesperson', label: 'Spokesperson', type: 'text' },
    { key: 'ai_generated', label: 'AI Generated', type: 'checkbox' },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'approved', 'used'] },
  ],
};

export const postCrisisAnalysisConfig = {
  title: 'Post-Crisis Analysis',
  isAI: true,
  apiGetAll: getPostCrisisAnalyses,
  apiGetOne: getPostCrisisAnalysis,
  apiCreate: createPostCrisisAnalysis,
  apiUpdate: updatePostCrisisAnalysis,
  apiDelete: deletePostCrisisAnalysis,
  aiGenerate: generatePostCrisisAnalysis,
  aiLabel: 'Generate Analysis',
  aiFields: [
    { key: 'crisis_summary', label: 'Crisis Summary', type: 'textarea', required: true },
    { key: 'actions_taken', label: 'Actions Taken', type: 'textarea', required: true },
    { key: 'timeline', label: 'Key Timeline Events', type: 'textarea' },
    { key: 'outcome', label: 'Outcome', type: 'textarea' },
  ],
  aiResponseField: 'ai_analysis',
  columns: [
    { key: 'title', label: 'Title' },
    { key: 'status', label: 'Status', badge: true },
    { key: 'crisis_id', label: 'Crisis ID' },
  ],
  fields: [
    { key: 'crisis_id', label: 'Crisis ID', type: 'number' },
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'summary', label: 'Summary', type: 'textarea' },
    { key: 'what_went_well', label: 'What Went Well', type: 'textarea' },
    { key: 'what_went_wrong', label: 'What Went Wrong', type: 'textarea' },
    { key: 'recommendations', label: 'Recommendations', type: 'textarea' },
    { key: 'metrics', label: 'Metrics', type: 'textarea' },
    { key: 'ai_analysis', label: 'AI Analysis', type: 'textarea' },
    { key: 'status', label: 'Status', type: 'select', options: ['draft', 'final'] },
  ],
};
